//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SONPV-PC\\MSSQL2008;Initial Catalog=QuanLyNganSach;User ID=sa")]
        public string QuanLyNganSachConnectionString {
            get {
                return ((string)(this["QuanLyNganSachConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQL2008;Initial Catalog=VPB;User ID=sa")]
        public string VPBConnectionString {
            get {
                return ((string)(this["VPBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HO-TTPTKD-KIENL;Initial Catalog=VPBReport;Persist Security Info=True;" +
            "User ID=sa")]
        public string VPBReportConnectionString {
            get {
                return ((string)(this["VPBReportConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HO-TTPTKD-KIENL;Initial Catalog=ReportTest;User ID=sa")]
        public string ReportTestConnectionString {
            get {
                return ((string)(this["ReportTestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HO-TTPTKD-KIENL;Initial Catalog=DASHBOARD;User ID=sa")]
        public string DASHBOARDConnectionString {
            get {
                return ((string)(this["DASHBOARDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HO-TTPTKD-KIENL;Initial Catalog=DASHBOARD.GENERAL;Persist Security In" +
            "fo=True;User ID=sa")]
        public string DASHBOARD_GENERALConnectionString {
            get {
                return ((string)(this["DASHBOARD_GENERALConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.39.36.80;Initial Catalog=DASHBOARD.GENERAL;User ID=sa")]
        public string DASHBOARD_GENERALConnectionString1 {
            get {
                return ((string)(this["DASHBOARD_GENERALConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HO-TTPTKD-KIENL;Initial Catalog=DASHBOARD.GENERAL;User ID=sa")]
        public string DASHBOARD_GENERALConnectionString2 {
            get {
                return ((string)(this["DASHBOARD_GENERALConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.39.36.80;Initial Catalog=VPBReportLocal;Persist Security Info=True" +
            ";User ID=sa")]
        public string VPBReportLocalConnectionString {
            get {
                return ((string)(this["VPBReportLocalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.39.36.80;Initial Catalog=VPBReport;Persist Security Info=True;User" +
            " ID=sa")]
        public string VPBReportConnectionString1 {
            get {
                return ((string)(this["VPBReportConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.39.36.80;Initial Catalog=DASHBOARD.GENERAL;Persist Security Info=T" +
            "rue;User ID=sa")]
        public string DASHBOARD_GENERALConnectionString3 {
            get {
                return ((string)(this["DASHBOARD_GENERALConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.36.76.12;Initial Catalog=DASHBOARD.GENERAL;Persist Security Info=T" +
            "rue;User ID=sa")]
        public string DASHBOARD_GENERALConnectionString4 {
            get {
                return ((string)(this["DASHBOARD_GENERALConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.36.76.12;Initial Catalog=VPBReport;User ID=sa")]
        public string VPBReportConnectionString2 {
            get {
                return ((string)(this["VPBReportConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=VPBReport;User ID=sa")]
        public string VPBReportConnectionString3 {
            get {
                return ((string)(this["VPBReportConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=VPBReport;User ID=sa;Password=abc@123")]
        public string VPBReportConnectionString4 {
            get {
                return ((string)(this["VPBReportConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=VPBReportBackup20170724;User ID=sa;Password=a" +
            "bc@123")]
        public string VPBReportBackup20170724ConnectionString {
            get {
                return ((string)(this["VPBReportBackup20170724ConnectionString"]));
            }
        }
    }
}
