#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VPBReport")]
	public partial class BIReportDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BIReportDataContext() : 
				base(global::DataContext.Properties.Settings.Default.VPBReportConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public BIReportDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BIReportDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BIReportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BIReportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspBIReportInsert")]
		public int uspBIReportInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> departmentId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string reportName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string client, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string emailClient, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string deadline, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> frequency, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string accountBackup, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isAuto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string urlReport)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), departmentId, reportName, client, emailClient, deadline, frequency, account, accountBackup, isAuto, description, urlReport);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspBIReportGetList")]
		public ISingleResult<uspBIReportGetListResult> uspBIReportGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string reportName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> departmentId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> frequency, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportName, departmentId, frequency, account, status);
			return ((ISingleResult<uspBIReportGetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspBIReportGetInfo")]
		public ISingleResult<uspBIReportGetInfoResult> uspBIReportGetInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> biReportListId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), biReportListId);
			return ((ISingleResult<uspBIReportGetInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspBiReportListGetInfo")]
		public ISingleResult<uspBiReportListGetInfoResult> uspBiReportListGetInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId);
			return ((ISingleResult<uspBiReportListGetInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspBIReportListUpdate")]
		public int uspBIReportListUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string reportName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string client, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string emailClient, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string deadline, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> frequency, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string accountBackup, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isAuto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string urlReport)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId, reportName, client, emailClient, deadline, frequency, account, accountBackup, isAuto, description, urlReport);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspBIReportListUpdateStatus")]
		public int uspBIReportListUpdateStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId, status);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class uspBIReportGetListResult
	{
		
		private int _BIReportListId;
		
		private int _DepartmentId;
		
		private string _ReportName;
		
		private string _ReportCode;
		
		private string _Client;
		
		private string _EmailClient;
		
		private string _Deadline;
		
		private string _Department;
		
		private string _Frequency;
		
		private string _Account;
		
		private int _Status;
		
		private string _AccountBackup;
		
		private int _IsAuto;
		
		private string _Description;
		
		private string _RequestForm;
		
		private int _TotalDownload;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public uspBIReportGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIReportListId", DbType="Int NOT NULL")]
		public int BIReportListId
		{
			get
			{
				return this._BIReportListId;
			}
			set
			{
				if ((this._BIReportListId != value))
				{
					this._BIReportListId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentId", DbType="Int NOT NULL")]
		public int DepartmentId
		{
			get
			{
				return this._DepartmentId;
			}
			set
			{
				if ((this._DepartmentId != value))
				{
					this._DepartmentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this._ReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportCode", DbType="VarChar(50)")]
		public string ReportCode
		{
			get
			{
				return this._ReportCode;
			}
			set
			{
				if ((this._ReportCode != value))
				{
					this._ReportCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this._Client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailClient", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailClient
		{
			get
			{
				return this._EmailClient;
			}
			set
			{
				if ((this._EmailClient != value))
				{
					this._EmailClient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deadline", DbType="VarChar(50)")]
		public string Deadline
		{
			get
			{
				return this._Deadline;
			}
			set
			{
				if ((this._Deadline != value))
				{
					this._Deadline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(2)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="VarChar(8)")]
		public string Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBackup", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountBackup
		{
			get
			{
				return this._AccountBackup;
			}
			set
			{
				if ((this._AccountBackup != value))
				{
					this._AccountBackup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAuto", DbType="Int NOT NULL")]
		public int IsAuto
		{
			get
			{
				return this._IsAuto;
			}
			set
			{
				if ((this._IsAuto != value))
				{
					this._IsAuto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestForm", DbType="VarChar(100)")]
		public string RequestForm
		{
			get
			{
				return this._RequestForm;
			}
			set
			{
				if ((this._RequestForm != value))
				{
					this._RequestForm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDownload", DbType="Int NOT NULL")]
		public int TotalDownload
		{
			get
			{
				return this._TotalDownload;
			}
			set
			{
				if ((this._TotalDownload != value))
				{
					this._TotalDownload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	public partial class uspBIReportGetInfoResult
	{
		
		private string _URLReport;
		
		public uspBIReportGetInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URLReport", DbType="NVarChar(MAX)")]
		public string URLReport
		{
			get
			{
				return this._URLReport;
			}
			set
			{
				if ((this._URLReport != value))
				{
					this._URLReport = value;
				}
			}
		}
	}
	
	public partial class uspBiReportListGetInfoResult
	{
		
		private int _BIReportListId;
		
		private int _DepartmentId;
		
		private string _ReportName;
		
		private string _Client;
		
		private string _EmailClient;
		
		private string _Deadline;
		
		private int _Frequency;
		
		private string _Description;
		
		private string _Account;
		
		private string _AccountBackup;
		
		private int _IsAuto;
		
		private string _URLReport;
		
		public uspBiReportListGetInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIReportListId", DbType="Int NOT NULL")]
		public int BIReportListId
		{
			get
			{
				return this._BIReportListId;
			}
			set
			{
				if ((this._BIReportListId != value))
				{
					this._BIReportListId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentId", DbType="Int NOT NULL")]
		public int DepartmentId
		{
			get
			{
				return this._DepartmentId;
			}
			set
			{
				if ((this._DepartmentId != value))
				{
					this._DepartmentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this._ReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this._Client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailClient", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailClient
		{
			get
			{
				return this._EmailClient;
			}
			set
			{
				if ((this._EmailClient != value))
				{
					this._EmailClient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deadline", DbType="VarChar(50)")]
		public string Deadline
		{
			get
			{
				return this._Deadline;
			}
			set
			{
				if ((this._Deadline != value))
				{
					this._Deadline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="Int NOT NULL")]
		public int Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBackup", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountBackup
		{
			get
			{
				return this._AccountBackup;
			}
			set
			{
				if ((this._AccountBackup != value))
				{
					this._AccountBackup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAuto", DbType="Int NOT NULL")]
		public int IsAuto
		{
			get
			{
				return this._IsAuto;
			}
			set
			{
				if ((this._IsAuto != value))
				{
					this._IsAuto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URLReport", DbType="NVarChar(MAX)")]
		public string URLReport
		{
			get
			{
				return this._URLReport;
			}
			set
			{
				if ((this._URLReport != value))
				{
					this._URLReport = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
