<?xml version="1.0" encoding="utf-8"?><Database Name="VPBReport" Class="BIReportDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=VPBReport;User ID=sa" SettingsObjectName="DataContext.Properties.Settings" SettingsPropertyName="VPBReportConnectionString4" Provider="System.Data.SqlClient" />
  <Function Name="dbo.uspBIReportInsert" Method="uspBIReportInsert">
    <Parameter Name="departmentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="reportName" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="client" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="emailClient" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="deadline" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="frequency" Type="System.Int32" DbType="Int" />
    <Parameter Name="account" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="accountBackup" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="isAuto" Type="System.Int32" DbType="Int" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="urlReport" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspBIReportGetList" Method="uspBIReportGetList">
    <Parameter Name="reportName" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="departmentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="frequency" Type="System.Int32" DbType="Int" />
    <Parameter Name="account" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspBIReportGetListResult">
      <Column Name="BIReportListId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ReportCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Client" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailClient" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deadline" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountBackup" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsAuto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RequestForm" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TotalDownload" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspBIReportGetInfo" Method="uspBIReportGetInfo">
    <Parameter Name="biReportListId" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspBIReportGetInfoResult">
      <Column Name="URLReport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspBiReportListGetInfo" Method="uspBiReportListGetInfo">
    <Parameter Name="reportListId" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspBiReportListGetInfoResult">
      <Column Name="BIReportListId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Client" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailClient" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deadline" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccountBackup" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsAuto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="URLReport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspBIReportListUpdate" Method="uspBIReportListUpdate">
    <Parameter Name="reportListId" Type="System.Int32" DbType="Int" />
    <Parameter Name="reportName" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="client" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="emailClient" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="deadline" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="frequency" Type="System.Int32" DbType="Int" />
    <Parameter Name="account" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="accountBackup" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="isAuto" Type="System.Int32" DbType="Int" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="urlReport" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspBIReportListUpdateStatus" Method="uspBIReportListUpdateStatus">
    <Parameter Name="reportListId" Type="System.Int32" DbType="Int" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>