#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VPBReport")]
	public partial class CodeManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CodeManagementDataContext() : 
				base(global::DataContext.Properties.Settings.Default.VPBReportConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public CodeManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CodeManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CodeManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CodeManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspCodeListCount")]
		public ISingleResult<uspCodeListCountResult> uspCodeListCount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(55)")] string account)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account);
			return ((ISingleResult<uspCodeListCountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspCodelistDelete")]
		public int uspCodelistDelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> field)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, code, field);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspCodeListEdit")]
		public int uspCodeListEdit([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> code_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> field, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string segment, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> effective_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string requester, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, code_id, name, type, field, segment, effective_date, requester, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspCodeListGetFieldList")]
		public ISingleResult<uspCodeListGetFieldListResult> uspCodeListGetFieldList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspCodeListGetFieldListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspCodeListGetType")]
		public ISingleResult<uspCodeListGetTypeResult> uspCodeListGetType([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> field_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), field_id);
			return ((ISingleResult<uspCodeListGetTypeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspCodeListInsert")]
		public int uspCodeListInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(55)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> field, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string segment, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> effective_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string requester, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, code, name, type, field, segment, effective_date, requester, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspCodeListGetInfo")]
		public ISingleResult<uspCodeListGetInfoResult> uspCodeListGetInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> code_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code_id);
			return ((ISingleResult<uspCodeListGetInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspCodeListGetList")]
		public ISingleResult<uspCodeListGetListResult> uspCodeListGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> field, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string requester, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(125)")] string segment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROMDATE", DbType="DateTime")] System.Nullable<System.DateTime> fROMDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TODATE", DbType="DateTime")] System.Nullable<System.DateTime> tODATE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pagesize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOTALRECORD", DbType="Int")] ref System.Nullable<int> tOTALRECORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status, type, field, requester, segment, fROMDATE, tODATE, pagesize, page, tOTALRECORD);
			tOTALRECORD = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((ISingleResult<uspCodeListGetListResult>)(result.ReturnValue));
		}
	}
	
	public partial class uspCodeListCountResult
	{
		
		private System.Nullable<int> _FIELD_ID;
		
		private string _FIELD;
		
		private System.Nullable<int> _TYPE_ID;
		
		private string _TYPE;
		
		private System.Nullable<int> _NO_CODE;
		
		public uspCodeListCountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD_ID", DbType="Int")]
		public System.Nullable<int> FIELD_ID
		{
			get
			{
				return this._FIELD_ID;
			}
			set
			{
				if ((this._FIELD_ID != value))
				{
					this._FIELD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string FIELD
		{
			get
			{
				return this._FIELD;
			}
			set
			{
				if ((this._FIELD != value))
				{
					this._FIELD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_ID", DbType="Int")]
		public System.Nullable<int> TYPE_ID
		{
			get
			{
				return this._TYPE_ID;
			}
			set
			{
				if ((this._TYPE_ID != value))
				{
					this._TYPE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_CODE", DbType="Int")]
		public System.Nullable<int> NO_CODE
		{
			get
			{
				return this._NO_CODE;
			}
			set
			{
				if ((this._NO_CODE != value))
				{
					this._NO_CODE = value;
				}
			}
		}
	}
	
	public partial class uspCodeListGetFieldListResult
	{
		
		private System.Nullable<int> _FIELD_ID;
		
		private string _FIELD_NAME;
		
		public uspCodeListGetFieldListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD_ID", DbType="Int")]
		public System.Nullable<int> FIELD_ID
		{
			get
			{
				return this._FIELD_ID;
			}
			set
			{
				if ((this._FIELD_ID != value))
				{
					this._FIELD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD_NAME", DbType="NVarChar(255)")]
		public string FIELD_NAME
		{
			get
			{
				return this._FIELD_NAME;
			}
			set
			{
				if ((this._FIELD_NAME != value))
				{
					this._FIELD_NAME = value;
				}
			}
		}
	}
	
	public partial class uspCodeListGetTypeResult
	{
		
		private System.Nullable<int> _TYPE_ID;
		
		private string _TYPE_NAME;
		
		public uspCodeListGetTypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_ID", DbType="Int")]
		public System.Nullable<int> TYPE_ID
		{
			get
			{
				return this._TYPE_ID;
			}
			set
			{
				if ((this._TYPE_ID != value))
				{
					this._TYPE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_NAME", DbType="NVarChar(255)")]
		public string TYPE_NAME
		{
			get
			{
				return this._TYPE_NAME;
			}
			set
			{
				if ((this._TYPE_NAME != value))
				{
					this._TYPE_NAME = value;
				}
			}
		}
	}
	
	public partial class uspCodeListGetInfoResult
	{
		
		private int _CODE_ID;
		
		private string _CODE;
		
		private string _NAME;
		
		private System.Nullable<int> _TYPE;
		
		private string _TYPE_NAME;
		
		private System.Nullable<int> _FIELD;
		
		private string _FIELD_NAME;
		
		private string _SEGMENT;
		
		private System.Nullable<System.DateTime> _EFFECTIVE_DATE;
		
		private string _REQUESTER;
		
		private System.Nullable<int> _STATUS_ID;
		
		private string _STATUS;
		
		public uspCodeListGetInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE_ID", DbType="Int NOT NULL")]
		public int CODE_ID
		{
			get
			{
				return this._CODE_ID;
			}
			set
			{
				if ((this._CODE_ID != value))
				{
					this._CODE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(25)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Int")]
		public System.Nullable<int> TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_NAME", DbType="NVarChar(255)")]
		public string TYPE_NAME
		{
			get
			{
				return this._TYPE_NAME;
			}
			set
			{
				if ((this._TYPE_NAME != value))
				{
					this._TYPE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD", DbType="Int")]
		public System.Nullable<int> FIELD
		{
			get
			{
				return this._FIELD;
			}
			set
			{
				if ((this._FIELD != value))
				{
					this._FIELD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD_NAME", DbType="NVarChar(255)")]
		public string FIELD_NAME
		{
			get
			{
				return this._FIELD_NAME;
			}
			set
			{
				if ((this._FIELD_NAME != value))
				{
					this._FIELD_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGMENT", DbType="NVarChar(25)")]
		public string SEGMENT
		{
			get
			{
				return this._SEGMENT;
			}
			set
			{
				if ((this._SEGMENT != value))
				{
					this._SEGMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFFECTIVE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EFFECTIVE_DATE
		{
			get
			{
				return this._EFFECTIVE_DATE;
			}
			set
			{
				if ((this._EFFECTIVE_DATE != value))
				{
					this._EFFECTIVE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUESTER", DbType="NVarChar(10)")]
		public string REQUESTER
		{
			get
			{
				return this._REQUESTER;
			}
			set
			{
				if ((this._REQUESTER != value))
				{
					this._REQUESTER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_ID", DbType="Int")]
		public System.Nullable<int> STATUS_ID
		{
			get
			{
				return this._STATUS_ID;
			}
			set
			{
				if ((this._STATUS_ID != value))
				{
					this._STATUS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
	}
	
	public partial class uspCodeListGetListResult
	{
		
		private System.Nullable<long> _RN;
		
		private int _CODE_ID;
		
		private string _CODE;
		
		private string _NAME;
		
		private System.Nullable<int> _TYPE;
		
		private string _TYPE_NAME;
		
		private System.Nullable<int> _FIELD;
		
		private string _FIELD_NAME;
		
		private string _SEGMENT;
		
		private System.Nullable<System.DateTime> _EFFECTIVE_DATE;
		
		private string _REQUESTER;
		
		private string _STATUS;
		
		public uspCodeListGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RN", DbType="BigInt")]
		public System.Nullable<long> RN
		{
			get
			{
				return this._RN;
			}
			set
			{
				if ((this._RN != value))
				{
					this._RN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE_ID", DbType="Int NOT NULL")]
		public int CODE_ID
		{
			get
			{
				return this._CODE_ID;
			}
			set
			{
				if ((this._CODE_ID != value))
				{
					this._CODE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(25)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Int")]
		public System.Nullable<int> TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_NAME", DbType="NVarChar(255)")]
		public string TYPE_NAME
		{
			get
			{
				return this._TYPE_NAME;
			}
			set
			{
				if ((this._TYPE_NAME != value))
				{
					this._TYPE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD", DbType="Int")]
		public System.Nullable<int> FIELD
		{
			get
			{
				return this._FIELD;
			}
			set
			{
				if ((this._FIELD != value))
				{
					this._FIELD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD_NAME", DbType="NVarChar(255)")]
		public string FIELD_NAME
		{
			get
			{
				return this._FIELD_NAME;
			}
			set
			{
				if ((this._FIELD_NAME != value))
				{
					this._FIELD_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGMENT", DbType="NVarChar(25)")]
		public string SEGMENT
		{
			get
			{
				return this._SEGMENT;
			}
			set
			{
				if ((this._SEGMENT != value))
				{
					this._SEGMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFFECTIVE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EFFECTIVE_DATE
		{
			get
			{
				return this._EFFECTIVE_DATE;
			}
			set
			{
				if ((this._EFFECTIVE_DATE != value))
				{
					this._EFFECTIVE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUESTER", DbType="NVarChar(10)")]
		public string REQUESTER
		{
			get
			{
				return this._REQUESTER;
			}
			set
			{
				if ((this._REQUESTER != value))
				{
					this._REQUESTER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
