<?xml version="1.0" encoding="utf-8"?><Database Name="VPB" Class="DepartmentDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQL2008;Initial Catalog=VPB;User ID=sa" SettingsObjectName="DataContext.Properties.Settings" SettingsPropertyName="VPBConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.uspDepartmentDelete" Method="uspDepartmentDelete">
    <Parameter Name="departmentId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspDepartmentGetById" Method="uspDepartmentGetById">
    <Parameter Name="departmentId" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspDepartmentGetByIdResult">
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AdminId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspDepartmentGetList" Method="uspDepartmentGetList">
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspDepartmentGetListResult">
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AdminId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspDepartmentInsert" Method="uspDepartmentInsert">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="adminId" Type="System.Int32" DbType="Int" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspDepartmentUpdate" Method="uspDepartmentUpdate">
    <Parameter Name="departmentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="adminId" Type="System.Int32" DbType="Int" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminGetForDepartment" Method="uspAdminGetForDepartment">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="type" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspAdminGetForDepartmentResult">
      <Column Name="AdminId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminUpdateDepartment" Method="uspAdminUpdateDepartment">
    <Parameter Name="adminIds" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="departmentId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminNotInDepartmentGetList" Method="uspAdminNotInDepartmentGetList">
    <ElementType Name="uspAdminNotInDepartmentGetListResult">
      <Column Name="AdminId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminGetListByDepartment" Method="uspAdminGetListByDepartment">
    <Parameter Name="departmentId" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspAdminGetListByDepartmentResult">
      <Column Name="AdminId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspDepartmentRemoveMember" Method="uspDepartmentRemoveMember">
    <Parameter Name="adminId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspDepartmentCheckManager" Method="uspDepartmentCheckManager">
    <Parameter Name="adminId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>