#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VPBReport")]
	public partial class ETLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ETLDataContext() : 
				base(global::DataContext.Properties.Settings.Default.VPBReportConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public ETLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ETLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ETLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ETLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspETLDictionaryDelete")]
		public int uspETLDictionaryDelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspETLDictionaryGetInfo")]
		public ISingleResult<uspETLDictionaryGetInfoResult> uspETLDictionaryGetInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<uspETLDictionaryGetInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspETLDictionaryGetList")]
		public ISingleResult<uspETLDictionaryGetListResult> uspETLDictionaryGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string db, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string table)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), db, table);
			return ((ISingleResult<uspETLDictionaryGetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspETLDictionaryInsert")]
		public int uspETLDictionaryInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string package, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string controlFlow, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sourceDb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sourceTable, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string destDb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string destTable, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string note)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), package, controlFlow, sourceDb, sourceTable, destDb, destTable, note);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspETLDictionaryUpdate")]
		public int uspETLDictionaryUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string package, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string controlFlow, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sourceDb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sourceTable, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string destDb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string destTable, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string note)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, package, controlFlow, sourceDb, sourceTable, destDb, destTable, note);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class uspETLDictionaryGetInfoResult
	{
		
		private int _ID;
		
		private string _PACKAGE;
		
		private string _CONTROL_FLOW;
		
		private string _SOURCE_DB;
		
		private string _SOURCE_TABLE;
		
		private string _DEST_DB;
		
		private string _DEST_TABLE;
		
		private string _NOTES;
		
		public uspETLDictionaryGetInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKAGE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PACKAGE
		{
			get
			{
				return this._PACKAGE;
			}
			set
			{
				if ((this._PACKAGE != value))
				{
					this._PACKAGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTROL_FLOW", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CONTROL_FLOW
		{
			get
			{
				return this._CONTROL_FLOW;
			}
			set
			{
				if ((this._CONTROL_FLOW != value))
				{
					this._CONTROL_FLOW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCE_DB", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SOURCE_DB
		{
			get
			{
				return this._SOURCE_DB;
			}
			set
			{
				if ((this._SOURCE_DB != value))
				{
					this._SOURCE_DB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCE_TABLE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SOURCE_TABLE
		{
			get
			{
				return this._SOURCE_TABLE;
			}
			set
			{
				if ((this._SOURCE_TABLE != value))
				{
					this._SOURCE_TABLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEST_DB", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DEST_DB
		{
			get
			{
				return this._DEST_DB;
			}
			set
			{
				if ((this._DEST_DB != value))
				{
					this._DEST_DB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEST_TABLE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DEST_TABLE
		{
			get
			{
				return this._DEST_TABLE;
			}
			set
			{
				if ((this._DEST_TABLE != value))
				{
					this._DEST_TABLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTES", DbType="NVarChar(100)")]
		public string NOTES
		{
			get
			{
				return this._NOTES;
			}
			set
			{
				if ((this._NOTES != value))
				{
					this._NOTES = value;
				}
			}
		}
	}
	
	public partial class uspETLDictionaryGetListResult
	{
		
		private int _ID;
		
		private string _PACKAGE;
		
		private string _CONTROL_FLOW;
		
		private string _SOURCE_DB;
		
		private string _SOURCE_TABLE;
		
		private string _DEST_DB;
		
		private string _DEST_TABLE;
		
		private string _NOTES;
		
		public uspETLDictionaryGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKAGE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PACKAGE
		{
			get
			{
				return this._PACKAGE;
			}
			set
			{
				if ((this._PACKAGE != value))
				{
					this._PACKAGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTROL_FLOW", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CONTROL_FLOW
		{
			get
			{
				return this._CONTROL_FLOW;
			}
			set
			{
				if ((this._CONTROL_FLOW != value))
				{
					this._CONTROL_FLOW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCE_DB", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SOURCE_DB
		{
			get
			{
				return this._SOURCE_DB;
			}
			set
			{
				if ((this._SOURCE_DB != value))
				{
					this._SOURCE_DB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCE_TABLE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SOURCE_TABLE
		{
			get
			{
				return this._SOURCE_TABLE;
			}
			set
			{
				if ((this._SOURCE_TABLE != value))
				{
					this._SOURCE_TABLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEST_DB", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DEST_DB
		{
			get
			{
				return this._DEST_DB;
			}
			set
			{
				if ((this._DEST_DB != value))
				{
					this._DEST_DB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEST_TABLE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DEST_TABLE
		{
			get
			{
				return this._DEST_TABLE;
			}
			set
			{
				if ((this._DEST_TABLE != value))
				{
					this._DEST_TABLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTES", DbType="NVarChar(100)")]
		public string NOTES
		{
			get
			{
				return this._NOTES;
			}
			set
			{
				if ((this._NOTES != value))
				{
					this._NOTES = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
