#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VPBReportLocal")]
	public partial class HRDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public HRDataContext() : 
				base(global::DataContext.Properties.Settings.Default.VPBReportLocalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HRDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHRGetList")]
		public ISingleResult<uspHRGetListResult> uspHRGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleSupport, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string saleCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string saleName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string team, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> totalRecord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleSupport, saleCode, saleName, team, page, pageSize, totalRecord);
			totalRecord = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((ISingleResult<uspHRGetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHRGetTeam")]
		public ISingleResult<uspHRGetTeamResult> uspHRGetTeam([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleSupport)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleSupport);
			return ((ISingleResult<uspHRGetTeamResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHrSubPositionGetList")]
		public ISingleResult<uspHrSubPositionGetListResult> uspHrSubPositionGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleSupport, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string channel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string position)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleSupport, channel, position);
			return ((ISingleResult<uspHrSubPositionGetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHrPositionGetList")]
		public ISingleResult<uspHrPositionGetListResult> uspHrPositionGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleSupport, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string channel)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleSupport, channel);
			return ((ISingleResult<uspHrPositionGetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHrChannelGetList")]
		public ISingleResult<uspHrChannelGetListResult> uspHrChannelGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleSupport)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleSupport);
			return ((ISingleResult<uspHrChannelGetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHrSaleOff")]
		public int uspHrSaleOff([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleSupport, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string saleCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dateOff)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleSupport, saleCode, dateOff);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHrInsert")]
		public int uspHrInsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleSupport, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string dao, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string hrStaff, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string saleNameTv, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string gender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string branchCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string channel, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string team, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string position, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string subPosition, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dateStart, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nationalId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string phone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dob, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string payroll, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string note)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleSupport, dao, hrStaff, saleName, saleNameTv, gender, branchCode, channel, team, position, subPosition, dateStart, nationalId, phone, dob, email, payroll, address, note);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHrGetInfo")]
		public ISingleResult<uspHrGetInfoResult> uspHrGetInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string saleCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleCode);
			return ((ISingleResult<uspHrGetInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHRGetListNewSales")]
		public ISingleResult<uspHRGetListNewSalesResult> uspHRGetListNewSales([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleSupport, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleSupport, date);
			return ((ISingleResult<uspHRGetListNewSalesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHrGetListByMonth")]
		public ISingleResult<uspHrGetListByMonthResult> uspHrGetListByMonth([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleSupport, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string month)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleSupport, month);
			return ((ISingleResult<uspHrGetListByMonthResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspHrUpdate")]
		public int uspHrUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleSupport, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string saleCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string dao, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string hrStaff, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string saleName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string saleNameTv, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string gender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string channel, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string team, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dateStart, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nationalId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string phone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dob, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string payroll, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string note)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleSupport, saleCode, dao, hrStaff, saleName, saleNameTv, gender, channel, team, dateStart, nationalId, phone, dob, email, payroll, address, note);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class uspHRGetListResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private string _SALE_CODE;
		
		private string _DAO;
		
		private string _SALE_NAME;
		
		private string _SALE_NAME_TV;
		
		private string _GENDER;
		
		private string _REGION;
		
		private string _BRANCH_CODE;
		
		private string _PROJECT;
		
		private string _CHANNEL;
		
		private string _TEAM;
		
		private string _POSITION;
		
		private string _SUB_POSITION;
		
		private System.Nullable<short> _STATUS;
		
		private System.Nullable<System.DateTime> _DATE_SALES_START;
		
		private System.Nullable<System.DateTime> _DATE_SALES_OFF;
		
		private System.Nullable<System.DateTime> _DOB_SALES;
		
		private string _NATIONAL_ID;
		
		private string _PHONE;
		
		private string _EMAIL;
		
		private string _NOTE;
		
		private string _PAYROLL_ACCT;
		
		private string _HR_STAFF;
		
		private string _ADDRESS;
		
		private string _FINGERPRINT;
		
		private string _CODE_FINN;
		
		private string _RESIGNED_REASON;
		
		public uspHRGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SALE_CODE
		{
			get
			{
				return this._SALE_CODE;
			}
			set
			{
				if ((this._SALE_CODE != value))
				{
					this._SALE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAO", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DAO
		{
			get
			{
				return this._DAO;
			}
			set
			{
				if ((this._DAO != value))
				{
					this._DAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_NAME", DbType="VarChar(200)")]
		public string SALE_NAME
		{
			get
			{
				return this._SALE_NAME;
			}
			set
			{
				if ((this._SALE_NAME != value))
				{
					this._SALE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_NAME_TV", DbType="NVarChar(500)")]
		public string SALE_NAME_TV
		{
			get
			{
				return this._SALE_NAME_TV;
			}
			set
			{
				if ((this._SALE_NAME_TV != value))
				{
					this._SALE_NAME_TV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(10)")]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGION", DbType="VarChar(50)")]
		public string REGION
		{
			get
			{
				return this._REGION;
			}
			set
			{
				if ((this._REGION != value))
				{
					this._REGION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CODE", DbType="VarChar(20)")]
		public string BRANCH_CODE
		{
			get
			{
				return this._BRANCH_CODE;
			}
			set
			{
				if ((this._BRANCH_CODE != value))
				{
					this._BRANCH_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJECT", DbType="VarChar(50)")]
		public string PROJECT
		{
			get
			{
				return this._PROJECT;
			}
			set
			{
				if ((this._PROJECT != value))
				{
					this._PROJECT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="VarChar(50)")]
		public string CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM", DbType="VarChar(20)")]
		public string TEAM
		{
			get
			{
				return this._TEAM;
			}
			set
			{
				if ((this._TEAM != value))
				{
					this._TEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="VarChar(50)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this._POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_POSITION", DbType="VarChar(50)")]
		public string SUB_POSITION
		{
			get
			{
				return this._SUB_POSITION;
			}
			set
			{
				if ((this._SUB_POSITION != value))
				{
					this._SUB_POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="SmallInt")]
		public System.Nullable<short> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SALES_START", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_SALES_START
		{
			get
			{
				return this._DATE_SALES_START;
			}
			set
			{
				if ((this._DATE_SALES_START != value))
				{
					this._DATE_SALES_START = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SALES_OFF", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_SALES_OFF
		{
			get
			{
				return this._DATE_SALES_OFF;
			}
			set
			{
				if ((this._DATE_SALES_OFF != value))
				{
					this._DATE_SALES_OFF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB_SALES", DbType="Date")]
		public System.Nullable<System.DateTime> DOB_SALES
		{
			get
			{
				return this._DOB_SALES;
			}
			set
			{
				if ((this._DOB_SALES != value))
				{
					this._DOB_SALES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATIONAL_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NATIONAL_ID
		{
			get
			{
				return this._NATIONAL_ID;
			}
			set
			{
				if ((this._NATIONAL_ID != value))
				{
					this._NATIONAL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this._PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(500)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYROLL_ACCT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PAYROLL_ACCT
		{
			get
			{
				return this._PAYROLL_ACCT;
			}
			set
			{
				if ((this._PAYROLL_ACCT != value))
				{
					this._PAYROLL_ACCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HR_STAFF", DbType="VarChar(50)")]
		public string HR_STAFF
		{
			get
			{
				return this._HR_STAFF;
			}
			set
			{
				if ((this._HR_STAFF != value))
				{
					this._HR_STAFF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINGERPRINT", DbType="VarChar(100)")]
		public string FINGERPRINT
		{
			get
			{
				return this._FINGERPRINT;
			}
			set
			{
				if ((this._FINGERPRINT != value))
				{
					this._FINGERPRINT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE_FINN", DbType="NVarChar(10)")]
		public string CODE_FINN
		{
			get
			{
				return this._CODE_FINN;
			}
			set
			{
				if ((this._CODE_FINN != value))
				{
					this._CODE_FINN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIGNED_REASON", DbType="NVarChar(500)")]
		public string RESIGNED_REASON
		{
			get
			{
				return this._RESIGNED_REASON;
			}
			set
			{
				if ((this._RESIGNED_REASON != value))
				{
					this._RESIGNED_REASON = value;
				}
			}
		}
	}
	
	public partial class uspHRGetTeamResult
	{
		
		private string _TEAM;
		
		public uspHRGetTeamResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM", DbType="VarChar(20)")]
		public string TEAM
		{
			get
			{
				return this._TEAM;
			}
			set
			{
				if ((this._TEAM != value))
				{
					this._TEAM = value;
				}
			}
		}
	}
	
	public partial class uspHrSubPositionGetListResult
	{
		
		private string _SUB_POSITION;
		
		public uspHrSubPositionGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_POSITION", DbType="NVarChar(255)")]
		public string SUB_POSITION
		{
			get
			{
				return this._SUB_POSITION;
			}
			set
			{
				if ((this._SUB_POSITION != value))
				{
					this._SUB_POSITION = value;
				}
			}
		}
	}
	
	public partial class uspHrPositionGetListResult
	{
		
		private string _POSITION;
		
		public uspHrPositionGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="NVarChar(255)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this._POSITION = value;
				}
			}
		}
	}
	
	public partial class uspHrChannelGetListResult
	{
		
		private string _CHANNEL;
		
		public uspHrChannelGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="NVarChar(255)")]
		public string CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
	}
	
	public partial class uspHrGetInfoResult
	{
		
		private string _SALE_CODE;
		
		private string _DAO;
		
		private string _HR_STAFF;
		
		private string _SALE_NAME;
		
		private string _SALE_NAME_TV;
		
		private string _GENDER;
		
		private string _REGION;
		
		private string _BRANCH_CODE;
		
		private string _PROJECT;
		
		private string _CHANNEL;
		
		private string _TEAM;
		
		private string _POSITION;
		
		private string _SUB_POSITION;
		
		private System.Nullable<System.DateTime> _DATE_SALES_START;
		
		private System.Nullable<System.DateTime> _DATE_SALES_OFF;
		
		private System.DateTime _DOB_SALES;
		
		private string _NATIONAL_ID;
		
		private string _PHONE;
		
		private string _EMAIL;
		
		private string _NOTE;
		
		private string _PAYROLL_ACCT;
		
		private string _ADDRESS;
		
		public uspHrGetInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SALE_CODE
		{
			get
			{
				return this._SALE_CODE;
			}
			set
			{
				if ((this._SALE_CODE != value))
				{
					this._SALE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAO", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DAO
		{
			get
			{
				return this._DAO;
			}
			set
			{
				if ((this._DAO != value))
				{
					this._DAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HR_STAFF", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HR_STAFF
		{
			get
			{
				return this._HR_STAFF;
			}
			set
			{
				if ((this._HR_STAFF != value))
				{
					this._HR_STAFF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_NAME", DbType="VarChar(200)")]
		public string SALE_NAME
		{
			get
			{
				return this._SALE_NAME;
			}
			set
			{
				if ((this._SALE_NAME != value))
				{
					this._SALE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_NAME_TV", DbType="NVarChar(500)")]
		public string SALE_NAME_TV
		{
			get
			{
				return this._SALE_NAME_TV;
			}
			set
			{
				if ((this._SALE_NAME_TV != value))
				{
					this._SALE_NAME_TV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(10)")]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGION", DbType="VarChar(50)")]
		public string REGION
		{
			get
			{
				return this._REGION;
			}
			set
			{
				if ((this._REGION != value))
				{
					this._REGION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CODE", DbType="VarChar(20)")]
		public string BRANCH_CODE
		{
			get
			{
				return this._BRANCH_CODE;
			}
			set
			{
				if ((this._BRANCH_CODE != value))
				{
					this._BRANCH_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJECT", DbType="VarChar(50)")]
		public string PROJECT
		{
			get
			{
				return this._PROJECT;
			}
			set
			{
				if ((this._PROJECT != value))
				{
					this._PROJECT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="VarChar(50)")]
		public string CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM", DbType="VarChar(20)")]
		public string TEAM
		{
			get
			{
				return this._TEAM;
			}
			set
			{
				if ((this._TEAM != value))
				{
					this._TEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="VarChar(50)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this._POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_POSITION", DbType="VarChar(50)")]
		public string SUB_POSITION
		{
			get
			{
				return this._SUB_POSITION;
			}
			set
			{
				if ((this._SUB_POSITION != value))
				{
					this._SUB_POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SALES_START", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_SALES_START
		{
			get
			{
				return this._DATE_SALES_START;
			}
			set
			{
				if ((this._DATE_SALES_START != value))
				{
					this._DATE_SALES_START = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SALES_OFF", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_SALES_OFF
		{
			get
			{
				return this._DATE_SALES_OFF;
			}
			set
			{
				if ((this._DATE_SALES_OFF != value))
				{
					this._DATE_SALES_OFF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB_SALES", DbType="Date NOT NULL")]
		public System.DateTime DOB_SALES
		{
			get
			{
				return this._DOB_SALES;
			}
			set
			{
				if ((this._DOB_SALES != value))
				{
					this._DOB_SALES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATIONAL_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NATIONAL_ID
		{
			get
			{
				return this._NATIONAL_ID;
			}
			set
			{
				if ((this._NATIONAL_ID != value))
				{
					this._NATIONAL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this._PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYROLL_ACCT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PAYROLL_ACCT
		{
			get
			{
				return this._PAYROLL_ACCT;
			}
			set
			{
				if ((this._PAYROLL_ACCT != value))
				{
					this._PAYROLL_ACCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
	}
	
	public partial class uspHRGetListNewSalesResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private string _SALE_CODE;
		
		private string _DAO;
		
		private string _SALE_NAME;
		
		private string _SALE_NAME_TV;
		
		private string _GENDER;
		
		private string _REGION;
		
		private string _BRANCH_CODE;
		
		private string _PROJECT;
		
		private string _CHANNEL;
		
		private string _TEAM;
		
		private string _POSITION;
		
		private string _SUB_POSITION;
		
		private System.Nullable<short> _STATUS;
		
		private System.Nullable<System.DateTime> _DATE_SALES_START;
		
		private System.Nullable<System.DateTime> _DATE_SALES_OFF;
		
		private System.DateTime _DOB_SALES;
		
		private string _NATIONAL_ID;
		
		private string _PHONE;
		
		private string _EMAIL;
		
		private string _NOTE;
		
		private string _PAYROLL_ACCT;
		
		private string _HR_STAFF;
		
		private string _ADDRESS;
		
		private string _FINGERPRINT;
		
		private string _CODE_FINN;
		
		private string _RESIGNED_REASON;
		
		public uspHRGetListNewSalesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SALE_CODE
		{
			get
			{
				return this._SALE_CODE;
			}
			set
			{
				if ((this._SALE_CODE != value))
				{
					this._SALE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAO", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DAO
		{
			get
			{
				return this._DAO;
			}
			set
			{
				if ((this._DAO != value))
				{
					this._DAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_NAME", DbType="VarChar(200)")]
		public string SALE_NAME
		{
			get
			{
				return this._SALE_NAME;
			}
			set
			{
				if ((this._SALE_NAME != value))
				{
					this._SALE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_NAME_TV", DbType="NVarChar(500)")]
		public string SALE_NAME_TV
		{
			get
			{
				return this._SALE_NAME_TV;
			}
			set
			{
				if ((this._SALE_NAME_TV != value))
				{
					this._SALE_NAME_TV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(10)")]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGION", DbType="VarChar(50)")]
		public string REGION
		{
			get
			{
				return this._REGION;
			}
			set
			{
				if ((this._REGION != value))
				{
					this._REGION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CODE", DbType="VarChar(20)")]
		public string BRANCH_CODE
		{
			get
			{
				return this._BRANCH_CODE;
			}
			set
			{
				if ((this._BRANCH_CODE != value))
				{
					this._BRANCH_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJECT", DbType="VarChar(50)")]
		public string PROJECT
		{
			get
			{
				return this._PROJECT;
			}
			set
			{
				if ((this._PROJECT != value))
				{
					this._PROJECT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="VarChar(50)")]
		public string CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM", DbType="VarChar(20)")]
		public string TEAM
		{
			get
			{
				return this._TEAM;
			}
			set
			{
				if ((this._TEAM != value))
				{
					this._TEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="VarChar(50)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this._POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_POSITION", DbType="VarChar(50)")]
		public string SUB_POSITION
		{
			get
			{
				return this._SUB_POSITION;
			}
			set
			{
				if ((this._SUB_POSITION != value))
				{
					this._SUB_POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="SmallInt")]
		public System.Nullable<short> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SALES_START", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_SALES_START
		{
			get
			{
				return this._DATE_SALES_START;
			}
			set
			{
				if ((this._DATE_SALES_START != value))
				{
					this._DATE_SALES_START = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SALES_OFF", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_SALES_OFF
		{
			get
			{
				return this._DATE_SALES_OFF;
			}
			set
			{
				if ((this._DATE_SALES_OFF != value))
				{
					this._DATE_SALES_OFF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB_SALES", DbType="Date NOT NULL")]
		public System.DateTime DOB_SALES
		{
			get
			{
				return this._DOB_SALES;
			}
			set
			{
				if ((this._DOB_SALES != value))
				{
					this._DOB_SALES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATIONAL_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NATIONAL_ID
		{
			get
			{
				return this._NATIONAL_ID;
			}
			set
			{
				if ((this._NATIONAL_ID != value))
				{
					this._NATIONAL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this._PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(500)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYROLL_ACCT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PAYROLL_ACCT
		{
			get
			{
				return this._PAYROLL_ACCT;
			}
			set
			{
				if ((this._PAYROLL_ACCT != value))
				{
					this._PAYROLL_ACCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HR_STAFF", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HR_STAFF
		{
			get
			{
				return this._HR_STAFF;
			}
			set
			{
				if ((this._HR_STAFF != value))
				{
					this._HR_STAFF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINGERPRINT", DbType="VarChar(100)")]
		public string FINGERPRINT
		{
			get
			{
				return this._FINGERPRINT;
			}
			set
			{
				if ((this._FINGERPRINT != value))
				{
					this._FINGERPRINT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE_FINN", DbType="NVarChar(10)")]
		public string CODE_FINN
		{
			get
			{
				return this._CODE_FINN;
			}
			set
			{
				if ((this._CODE_FINN != value))
				{
					this._CODE_FINN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIGNED_REASON", DbType="NVarChar(500)")]
		public string RESIGNED_REASON
		{
			get
			{
				return this._RESIGNED_REASON;
			}
			set
			{
				if ((this._RESIGNED_REASON != value))
				{
					this._RESIGNED_REASON = value;
				}
			}
		}
	}
	
	public partial class uspHrGetListByMonthResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private string _SALE_CODE;
		
		private string _DAO;
		
		private string _SALE_NAME;
		
		private string _SALE_NAME_TV;
		
		private string _GENDER;
		
		private string _REGION;
		
		private string _BRANCH_CODE;
		
		private string _PROJECT;
		
		private string _CHANNEL;
		
		private string _TEAM;
		
		private string _POSITION;
		
		private string _SUB_POSITION;
		
		private System.Nullable<short> _STATUS;
		
		private System.Nullable<System.DateTime> _DATE_SALES_START;
		
		private System.Nullable<System.DateTime> _DATE_SALES_OFF;
		
		private System.DateTime _DOB_SALES;
		
		private string _NATIONAL_ID;
		
		private string _PHONE;
		
		private string _EMAIL;
		
		private string _NOTE;
		
		private string _PAYROLL_ACCT;
		
		private string _HR_STAFF;
		
		private string _ADDRESS;
		
		private string _FINGERPRINT;
		
		private string _CODE_FINN;
		
		private string _RESIGNED_REASON;
		
		public uspHrGetListByMonthResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_CODE", DbType="VarChar(10)")]
		public string SALE_CODE
		{
			get
			{
				return this._SALE_CODE;
			}
			set
			{
				if ((this._SALE_CODE != value))
				{
					this._SALE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAO", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DAO
		{
			get
			{
				return this._DAO;
			}
			set
			{
				if ((this._DAO != value))
				{
					this._DAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_NAME", DbType="VarChar(200)")]
		public string SALE_NAME
		{
			get
			{
				return this._SALE_NAME;
			}
			set
			{
				if ((this._SALE_NAME != value))
				{
					this._SALE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_NAME_TV", DbType="NVarChar(500)")]
		public string SALE_NAME_TV
		{
			get
			{
				return this._SALE_NAME_TV;
			}
			set
			{
				if ((this._SALE_NAME_TV != value))
				{
					this._SALE_NAME_TV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(10)")]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGION", DbType="VarChar(50)")]
		public string REGION
		{
			get
			{
				return this._REGION;
			}
			set
			{
				if ((this._REGION != value))
				{
					this._REGION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CODE", DbType="VarChar(20)")]
		public string BRANCH_CODE
		{
			get
			{
				return this._BRANCH_CODE;
			}
			set
			{
				if ((this._BRANCH_CODE != value))
				{
					this._BRANCH_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJECT", DbType="VarChar(50)")]
		public string PROJECT
		{
			get
			{
				return this._PROJECT;
			}
			set
			{
				if ((this._PROJECT != value))
				{
					this._PROJECT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="VarChar(50)")]
		public string CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM", DbType="VarChar(20)")]
		public string TEAM
		{
			get
			{
				return this._TEAM;
			}
			set
			{
				if ((this._TEAM != value))
				{
					this._TEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="VarChar(50)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this._POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_POSITION", DbType="VarChar(50)")]
		public string SUB_POSITION
		{
			get
			{
				return this._SUB_POSITION;
			}
			set
			{
				if ((this._SUB_POSITION != value))
				{
					this._SUB_POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="SmallInt")]
		public System.Nullable<short> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SALES_START", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_SALES_START
		{
			get
			{
				return this._DATE_SALES_START;
			}
			set
			{
				if ((this._DATE_SALES_START != value))
				{
					this._DATE_SALES_START = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SALES_OFF", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_SALES_OFF
		{
			get
			{
				return this._DATE_SALES_OFF;
			}
			set
			{
				if ((this._DATE_SALES_OFF != value))
				{
					this._DATE_SALES_OFF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB_SALES", DbType="Date NOT NULL")]
		public System.DateTime DOB_SALES
		{
			get
			{
				return this._DOB_SALES;
			}
			set
			{
				if ((this._DOB_SALES != value))
				{
					this._DOB_SALES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATIONAL_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NATIONAL_ID
		{
			get
			{
				return this._NATIONAL_ID;
			}
			set
			{
				if ((this._NATIONAL_ID != value))
				{
					this._NATIONAL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this._PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(500)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYROLL_ACCT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PAYROLL_ACCT
		{
			get
			{
				return this._PAYROLL_ACCT;
			}
			set
			{
				if ((this._PAYROLL_ACCT != value))
				{
					this._PAYROLL_ACCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HR_STAFF", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HR_STAFF
		{
			get
			{
				return this._HR_STAFF;
			}
			set
			{
				if ((this._HR_STAFF != value))
				{
					this._HR_STAFF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINGERPRINT", DbType="VarChar(100)")]
		public string FINGERPRINT
		{
			get
			{
				return this._FINGERPRINT;
			}
			set
			{
				if ((this._FINGERPRINT != value))
				{
					this._FINGERPRINT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE_FINN", DbType="NVarChar(10)")]
		public string CODE_FINN
		{
			get
			{
				return this._CODE_FINN;
			}
			set
			{
				if ((this._CODE_FINN != value))
				{
					this._CODE_FINN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIGNED_REASON", DbType="NVarChar(500)")]
		public string RESIGNED_REASON
		{
			get
			{
				return this._RESIGNED_REASON;
			}
			set
			{
				if ((this._RESIGNED_REASON != value))
				{
					this._RESIGNED_REASON = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
