#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VPBReport")]
	public partial class IssueTrackingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public IssueTrackingDataContext() : 
				base(global::DataContext.Properties.Settings.Default.VPBReportConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public IssueTrackingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IssueTrackingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IssueTrackingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IssueTrackingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueCheckAccount")]
		public ISingleResult<uspDataIssueCheckAccountResult> uspDataIssueCheckAccount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account);
			return ((ISingleResult<uspDataIssueCheckAccountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueDelete")]
		public int uspDataIssueDelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string issue_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, issue_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueGetAccInfo")]
		public ISingleResult<uspDataIssueGetAccInfoResult> uspDataIssueGetAccInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account);
			return ((ISingleResult<uspDataIssueGetAccInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueListInsert")]
		public int uspDataIssueListInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> division1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> issue_status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> last_updated_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string summary, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string agreed_solution, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string note, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> first_date_fb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(55)")] string current_assignee, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> creation_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> est_deadline, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(55)")] string pic_bu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(55)")] string pic_bic, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> finishing_date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, division1, issue_status, last_updated_date, summary, agreed_solution, description, note, first_date_fb, current_assignee, creation_date, est_deadline, pic_bu, pic_bic, finishing_date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueExportExcel")]
		public ISingleResult<uspDataIssueExportExcelResult> uspDataIssueExportExcel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> division, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STATUS", DbType="Int")] System.Nullable<int> sTATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROMDATE", DbType="DateTime")] System.Nullable<System.DateTime> fROMDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TODATE", DbType="DateTime")] System.Nullable<System.DateTime> tODATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISSUE_CODE", DbType="NVarChar(255)")] string iSSUE_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PICBU", DbType="NVarChar(55)")] string pICBU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PICBIC", DbType="NVarChar(55)")] string pICBIC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, division, sTATUS, fROMDATE, tODATE, iSSUE_CODE, pICBU, pICBIC);
			return ((ISingleResult<uspDataIssueExportExcelResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueGetListPicBicc")]
		public ISingleResult<uspDataIssueGetListPicBiccResult> uspDataIssueGetListPicBicc()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspDataIssueGetListPicBiccResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueListGetList")]
		public ISingleResult<uspDataIssueListGetListResult> uspDataIssueListGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> division, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STATUS", DbType="Int")] System.Nullable<int> sTATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROMDATE", DbType="NVarChar(10)")] string fROMDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TODATE", DbType="NVarChar(10)")] string tODATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISSUE_CODE", DbType="NVarChar(255)")] string iSSUE_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PAGESIZE", DbType="Int")] System.Nullable<int> pAGESIZE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PAGE", DbType="Int")] System.Nullable<int> pAGE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PICBU", DbType="NVarChar(55)")] string pICBU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PICBIC", DbType="NVarChar(55)")] string pICBIC, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> updating_status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOTALRECORD", DbType="Int")] ref System.Nullable<int> tOTALRECORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, division, sTATUS, fROMDATE, tODATE, iSSUE_CODE, pAGESIZE, pAGE, pICBU, pICBIC, updating_status, tOTALRECORD);
			tOTALRECORD = ((System.Nullable<int>)(result.GetParameterValue(11)));
			return ((ISingleResult<uspDataIssueListGetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueGetInfo")]
		public ISingleResult<uspDataIssueGetInfoResult> uspDataIssueGetInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> issue_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, issue_ID);
			return ((ISingleResult<uspDataIssueGetInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueUpdate")]
		public int uspDataIssueUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACCOUNT", DbType="NVarChar(25)")] string aCCOUNT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> division, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISSUE_ID", DbType="Int")] System.Nullable<int> iSSUE_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISSUE_STATUS", DbType="Int")] System.Nullable<int> iSSUE_STATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUMMARY", DbType="NVarChar(MAX)")] string sUMMARY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AGREED_SOLUTION", DbType="NVarChar(MAX)")] string aGREED_SOLUTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPTION", DbType="NVarChar(MAX)")] string dESCRIPTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOTE", DbType="NVarChar(MAX)")] string nOTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FIRST_DATE_FB", DbType="DateTime")] System.Nullable<System.DateTime> fIRST_DATE_FB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CURRENT_ASSIGNEE", DbType="NVarChar(55)")] string cURRENT_ASSIGNEE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CREATION_DATE", DbType="DateTime")] System.Nullable<System.DateTime> cREATION_DATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EST_DEADLINE", DbType="DateTime")] System.Nullable<System.DateTime> eST_DEADLINE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FINISHING_DATE", DbType="DateTime")] System.Nullable<System.DateTime> fINISHING_DATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIC_BU", DbType="NVarChar(55)")] string pIC_BU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIC_BIC", DbType="NVarChar(55)")] string pIC_BIC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCCOUNT, division, iSSUE_ID, iSSUE_STATUS, sUMMARY, aGREED_SOLUTION, dESCRIPTION, nOTE, fIRST_DATE_FB, cURRENT_ASSIGNEE, cREATION_DATE, eST_DEADLINE, fINISHING_DATE, pIC_BU, pIC_BIC);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueConfirm")]
		public int uspDataIssueConfirm([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(55)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISSUE_ID", DbType="Int")] System.Nullable<int> iSSUE_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, iSSUE_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueGetListAllDivisionID")]
		public ISingleResult<uspDataIssueGetListAllDivisionIDResult> uspDataIssueGetListAllDivisionID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspDataIssueGetListAllDivisionIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDataIssueGetListDivisionID")]
		public ISingleResult<uspDataIssueGetListDivisionIDResult> uspDataIssueGetListDivisionID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account);
			return ((ISingleResult<uspDataIssueGetListDivisionIDResult>)(result.ReturnValue));
		}
	}
	
	public partial class uspDataIssueCheckAccountResult
	{
		
		private string _NAME;
		
		private System.Nullable<int> _DIVISION_ID;
		
		private int _DEPARTMENTID;
		
		private string _NAME1;
		
		public uspDataIssueCheckAccountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISION_ID", DbType="Int")]
		public System.Nullable<int> DIVISION_ID
		{
			get
			{
				return this._DIVISION_ID;
			}
			set
			{
				if ((this._DIVISION_ID != value))
				{
					this._DIVISION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENTID", DbType="Int NOT NULL")]
		public int DEPARTMENTID
		{
			get
			{
				return this._DEPARTMENTID;
			}
			set
			{
				if ((this._DEPARTMENTID != value))
				{
					this._DEPARTMENTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME1", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NAME1
		{
			get
			{
				return this._NAME1;
			}
			set
			{
				if ((this._NAME1 != value))
				{
					this._NAME1 = value;
				}
			}
		}
	}
	
	public partial class uspDataIssueGetAccInfoResult
	{
		
		private string _NAME;
		
		private System.Nullable<int> _DIVISION_ID;
		
		private string _Division_Name;
		
		private int _DEPARTMENTID;
		
		private string _NAME1;
		
		public uspDataIssueGetAccInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISION_ID", DbType="Int")]
		public System.Nullable<int> DIVISION_ID
		{
			get
			{
				return this._DIVISION_ID;
			}
			set
			{
				if ((this._DIVISION_ID != value))
				{
					this._DIVISION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division_Name", DbType="NVarChar(255)")]
		public string Division_Name
		{
			get
			{
				return this._Division_Name;
			}
			set
			{
				if ((this._Division_Name != value))
				{
					this._Division_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENTID", DbType="Int NOT NULL")]
		public int DEPARTMENTID
		{
			get
			{
				return this._DEPARTMENTID;
			}
			set
			{
				if ((this._DEPARTMENTID != value))
				{
					this._DEPARTMENTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME1", DbType="NVarChar(100)")]
		public string NAME1
		{
			get
			{
				return this._NAME1;
			}
			set
			{
				if ((this._NAME1 != value))
				{
					this._NAME1 = value;
				}
			}
		}
	}
	
	public partial class uspDataIssueExportExcelResult
	{
		
		private System.Nullable<long> _ROWNUMBER;
		
		private int _ISSUE_CODE;
		
		private string _DIVISION_NAME;
		
		private int _DIVISION_ID;
		
		private string _DIVISION_CODE;
		
		private string _SUMMARY;
		
		private string _Description;
		
		private string _agreed_solution;
		
		private string _ISSUE_STATUS;
		
		private string _NOTE;
		
		private string _CURRENT_ASSIGNEE;
		
		private System.Nullable<System.DateTime> _CREATION_DATE;
		
		private System.Nullable<System.DateTime> _First_date_fb;
		
		private System.Nullable<System.DateTime> _EST_DEADLINE;
		
		private System.DateTime _FINISHING_DATE;
		
		private double _PENDING_DAYS;
		
		private string _PIC_BU;
		
		private string _PIC_BIC;
		
		public uspDataIssueExportExcelResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWNUMBER", DbType="BigInt")]
		public System.Nullable<long> ROWNUMBER
		{
			get
			{
				return this._ROWNUMBER;
			}
			set
			{
				if ((this._ROWNUMBER != value))
				{
					this._ROWNUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISSUE_CODE", DbType="Int NOT NULL")]
		public int ISSUE_CODE
		{
			get
			{
				return this._ISSUE_CODE;
			}
			set
			{
				if ((this._ISSUE_CODE != value))
				{
					this._ISSUE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISION_NAME", DbType="NVarChar(255)")]
		public string DIVISION_NAME
		{
			get
			{
				return this._DIVISION_NAME;
			}
			set
			{
				if ((this._DIVISION_NAME != value))
				{
					this._DIVISION_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISION_ID", DbType="Int NOT NULL")]
		public int DIVISION_ID
		{
			get
			{
				return this._DIVISION_ID;
			}
			set
			{
				if ((this._DIVISION_ID != value))
				{
					this._DIVISION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISION_CODE", DbType="VarChar(10)")]
		public string DIVISION_CODE
		{
			get
			{
				return this._DIVISION_CODE;
			}
			set
			{
				if ((this._DIVISION_CODE != value))
				{
					this._DIVISION_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMMARY", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SUMMARY
		{
			get
			{
				return this._SUMMARY;
			}
			set
			{
				if ((this._SUMMARY != value))
				{
					this._SUMMARY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agreed_solution", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string agreed_solution
		{
			get
			{
				return this._agreed_solution;
			}
			set
			{
				if ((this._agreed_solution != value))
				{
					this._agreed_solution = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISSUE_STATUS", DbType="VarChar(25)")]
		public string ISSUE_STATUS
		{
			get
			{
				return this._ISSUE_STATUS;
			}
			set
			{
				if ((this._ISSUE_STATUS != value))
				{
					this._ISSUE_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENT_ASSIGNEE", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string CURRENT_ASSIGNEE
		{
			get
			{
				return this._CURRENT_ASSIGNEE;
			}
			set
			{
				if ((this._CURRENT_ASSIGNEE != value))
				{
					this._CURRENT_ASSIGNEE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATION_DATE
		{
			get
			{
				return this._CREATION_DATE;
			}
			set
			{
				if ((this._CREATION_DATE != value))
				{
					this._CREATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_date_fb", DbType="DateTime")]
		public System.Nullable<System.DateTime> First_date_fb
		{
			get
			{
				return this._First_date_fb;
			}
			set
			{
				if ((this._First_date_fb != value))
				{
					this._First_date_fb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_DEADLINE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EST_DEADLINE
		{
			get
			{
				return this._EST_DEADLINE;
			}
			set
			{
				if ((this._EST_DEADLINE != value))
				{
					this._EST_DEADLINE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINISHING_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime FINISHING_DATE
		{
			get
			{
				return this._FINISHING_DATE;
			}
			set
			{
				if ((this._FINISHING_DATE != value))
				{
					this._FINISHING_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PENDING_DAYS", DbType="Float NOT NULL")]
		public double PENDING_DAYS
		{
			get
			{
				return this._PENDING_DAYS;
			}
			set
			{
				if ((this._PENDING_DAYS != value))
				{
					this._PENDING_DAYS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_BU", DbType="NVarChar(55)")]
		public string PIC_BU
		{
			get
			{
				return this._PIC_BU;
			}
			set
			{
				if ((this._PIC_BU != value))
				{
					this._PIC_BU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_BIC", DbType="NVarChar(55)")]
		public string PIC_BIC
		{
			get
			{
				return this._PIC_BIC;
			}
			set
			{
				if ((this._PIC_BIC != value))
				{
					this._PIC_BIC = value;
				}
			}
		}
	}
	
	public partial class uspDataIssueGetListPicBiccResult
	{
		
		private string _name;
		
		private string _FullName;
		
		public uspDataIssueGetListPicBiccResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(250)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
	}
	
	public partial class uspDataIssueListGetListResult
	{
		
		private System.Nullable<long> _ROWNUMBER;
		
		private int _ISSUE_ID;
		
		private System.Nullable<int> _ISSUE_CODE;
		
		private string _DIVISION_CODE;
		
		private System.Nullable<int> _DIVISION;
		
		private string _SUMMARY;
		
		private string _ISSUE_STATUS;
		
		private string _CURRENT_ASSIGNEE;
		
		private System.Nullable<System.DateTime> _CREATION_DATE;
		
		private System.Nullable<System.DateTime> _EST_DEADLINE;
		
		private System.Nullable<System.DateTime> _FINISHING_DATE;
		
		private double _PENDING_DAYS;
		
		private string _PIC_BU;
		
		private string _PIC_BIC;
		
		private string _UPDATING_STATUS;
		
		private string _LAST_UPDATED_BY;
		
		private System.Nullable<System.DateTime> _LAST_UPDATED_DATE;
		
		public uspDataIssueListGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWNUMBER", DbType="BigInt")]
		public System.Nullable<long> ROWNUMBER
		{
			get
			{
				return this._ROWNUMBER;
			}
			set
			{
				if ((this._ROWNUMBER != value))
				{
					this._ROWNUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISSUE_ID", DbType="Int NOT NULL")]
		public int ISSUE_ID
		{
			get
			{
				return this._ISSUE_ID;
			}
			set
			{
				if ((this._ISSUE_ID != value))
				{
					this._ISSUE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISSUE_CODE", DbType="Int")]
		public System.Nullable<int> ISSUE_CODE
		{
			get
			{
				return this._ISSUE_CODE;
			}
			set
			{
				if ((this._ISSUE_CODE != value))
				{
					this._ISSUE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISION_CODE", DbType="VarChar(10)")]
		public string DIVISION_CODE
		{
			get
			{
				return this._DIVISION_CODE;
			}
			set
			{
				if ((this._DIVISION_CODE != value))
				{
					this._DIVISION_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISION", DbType="Int")]
		public System.Nullable<int> DIVISION
		{
			get
			{
				return this._DIVISION;
			}
			set
			{
				if ((this._DIVISION != value))
				{
					this._DIVISION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMMARY", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SUMMARY
		{
			get
			{
				return this._SUMMARY;
			}
			set
			{
				if ((this._SUMMARY != value))
				{
					this._SUMMARY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISSUE_STATUS", DbType="VarChar(25)")]
		public string ISSUE_STATUS
		{
			get
			{
				return this._ISSUE_STATUS;
			}
			set
			{
				if ((this._ISSUE_STATUS != value))
				{
					this._ISSUE_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENT_ASSIGNEE", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string CURRENT_ASSIGNEE
		{
			get
			{
				return this._CURRENT_ASSIGNEE;
			}
			set
			{
				if ((this._CURRENT_ASSIGNEE != value))
				{
					this._CURRENT_ASSIGNEE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATION_DATE
		{
			get
			{
				return this._CREATION_DATE;
			}
			set
			{
				if ((this._CREATION_DATE != value))
				{
					this._CREATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_DEADLINE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EST_DEADLINE
		{
			get
			{
				return this._EST_DEADLINE;
			}
			set
			{
				if ((this._EST_DEADLINE != value))
				{
					this._EST_DEADLINE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINISHING_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> FINISHING_DATE
		{
			get
			{
				return this._FINISHING_DATE;
			}
			set
			{
				if ((this._FINISHING_DATE != value))
				{
					this._FINISHING_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PENDING_DAYS", DbType="Float NOT NULL")]
		public double PENDING_DAYS
		{
			get
			{
				return this._PENDING_DAYS;
			}
			set
			{
				if ((this._PENDING_DAYS != value))
				{
					this._PENDING_DAYS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_BU", DbType="NVarChar(55)")]
		public string PIC_BU
		{
			get
			{
				return this._PIC_BU;
			}
			set
			{
				if ((this._PIC_BU != value))
				{
					this._PIC_BU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_BIC", DbType="NVarChar(55)")]
		public string PIC_BIC
		{
			get
			{
				return this._PIC_BIC;
			}
			set
			{
				if ((this._PIC_BIC != value))
				{
					this._PIC_BIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATING_STATUS", DbType="VarChar(20)")]
		public string UPDATING_STATUS
		{
			get
			{
				return this._UPDATING_STATUS;
			}
			set
			{
				if ((this._UPDATING_STATUS != value))
				{
					this._UPDATING_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATED_BY", DbType="NVarChar(10)")]
		public string LAST_UPDATED_BY
		{
			get
			{
				return this._LAST_UPDATED_BY;
			}
			set
			{
				if ((this._LAST_UPDATED_BY != value))
				{
					this._LAST_UPDATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAST_UPDATED_DATE
		{
			get
			{
				return this._LAST_UPDATED_DATE;
			}
			set
			{
				if ((this._LAST_UPDATED_DATE != value))
				{
					this._LAST_UPDATED_DATE = value;
				}
			}
		}
	}
	
	public partial class uspDataIssueGetInfoResult
	{
		
		private System.Nullable<int> _ISSUE_CODE;
		
		private System.Nullable<int> _DIVISION;
		
		private string _division_code;
		
		private string _Division_Name;
		
		private System.Nullable<int> _STATUS_ID;
		
		private string _STATUS;
		
		private string _SUMMARY;
		
		private string _AGREED_SOLUTION;
		
		private string _DESCRIPTION;
		
		private string _NOTE;
		
		private System.Nullable<System.DateTime> _FIRST_DATE_FB;
		
		private string _CURRENT_ASSIGNEE;
		
		private System.Nullable<System.DateTime> _CREATION_DATE;
		
		private System.Nullable<System.DateTime> _EST_DEADLINE;
		
		private System.Nullable<System.DateTime> _FINISHING_DATE;
		
		private System.Nullable<double> _PENDING_DAYS;
		
		private string _PIC_BU;
		
		private string _PIC_BIC;
		
		private System.Nullable<int> _O_ISSUE_CODE;
		
		private System.Nullable<int> _O_DIVISION;
		
		private string _O_DIVISION_CODE;
		
		private string _O_DIVISION_NAME;
		
		private System.Nullable<int> _O_STATUS_ID;
		
		private string _O_STATUS;
		
		private string _O_SUMMARY;
		
		private string _O_AGREED_SOLUTION;
		
		private string _O_DESCRIPTION;
		
		private string _O_NOTE;
		
		private System.Nullable<System.DateTime> _O_FIRST_DATE_FB;
		
		private string _O_CURRENT_ASSIGNEE;
		
		private System.Nullable<System.DateTime> _O_CREATION_DATE;
		
		private System.Nullable<System.DateTime> _O_EST_DEADLINE;
		
		private System.Nullable<System.DateTime> _O_FINISHING_DATE;
		
		private System.Nullable<double> _O_PENDING_DAYS;
		
		private string _O_PIC_BU;
		
		private string _O_PIC_BIC;
		
		public uspDataIssueGetInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISSUE_CODE", DbType="Int")]
		public System.Nullable<int> ISSUE_CODE
		{
			get
			{
				return this._ISSUE_CODE;
			}
			set
			{
				if ((this._ISSUE_CODE != value))
				{
					this._ISSUE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISION", DbType="Int")]
		public System.Nullable<int> DIVISION
		{
			get
			{
				return this._DIVISION;
			}
			set
			{
				if ((this._DIVISION != value))
				{
					this._DIVISION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division_code", DbType="NVarChar(50)")]
		public string division_code
		{
			get
			{
				return this._division_code;
			}
			set
			{
				if ((this._division_code != value))
				{
					this._division_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division_Name", DbType="NVarChar(255)")]
		public string Division_Name
		{
			get
			{
				return this._Division_Name;
			}
			set
			{
				if ((this._Division_Name != value))
				{
					this._Division_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_ID", DbType="Int")]
		public System.Nullable<int> STATUS_ID
		{
			get
			{
				return this._STATUS_ID;
			}
			set
			{
				if ((this._STATUS_ID != value))
				{
					this._STATUS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(255)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMMARY", DbType="NVarChar(MAX)")]
		public string SUMMARY
		{
			get
			{
				return this._SUMMARY;
			}
			set
			{
				if ((this._SUMMARY != value))
				{
					this._SUMMARY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGREED_SOLUTION", DbType="NVarChar(MAX)")]
		public string AGREED_SOLUTION
		{
			get
			{
				return this._AGREED_SOLUTION;
			}
			set
			{
				if ((this._AGREED_SOLUTION != value))
				{
					this._AGREED_SOLUTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(MAX)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this._DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(MAX)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_DATE_FB", DbType="DateTime")]
		public System.Nullable<System.DateTime> FIRST_DATE_FB
		{
			get
			{
				return this._FIRST_DATE_FB;
			}
			set
			{
				if ((this._FIRST_DATE_FB != value))
				{
					this._FIRST_DATE_FB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENT_ASSIGNEE", DbType="NVarChar(55)")]
		public string CURRENT_ASSIGNEE
		{
			get
			{
				return this._CURRENT_ASSIGNEE;
			}
			set
			{
				if ((this._CURRENT_ASSIGNEE != value))
				{
					this._CURRENT_ASSIGNEE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATION_DATE
		{
			get
			{
				return this._CREATION_DATE;
			}
			set
			{
				if ((this._CREATION_DATE != value))
				{
					this._CREATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_DEADLINE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EST_DEADLINE
		{
			get
			{
				return this._EST_DEADLINE;
			}
			set
			{
				if ((this._EST_DEADLINE != value))
				{
					this._EST_DEADLINE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINISHING_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> FINISHING_DATE
		{
			get
			{
				return this._FINISHING_DATE;
			}
			set
			{
				if ((this._FINISHING_DATE != value))
				{
					this._FINISHING_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PENDING_DAYS", DbType="Float")]
		public System.Nullable<double> PENDING_DAYS
		{
			get
			{
				return this._PENDING_DAYS;
			}
			set
			{
				if ((this._PENDING_DAYS != value))
				{
					this._PENDING_DAYS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_BU", DbType="NVarChar(55)")]
		public string PIC_BU
		{
			get
			{
				return this._PIC_BU;
			}
			set
			{
				if ((this._PIC_BU != value))
				{
					this._PIC_BU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_BIC", DbType="NVarChar(55)")]
		public string PIC_BIC
		{
			get
			{
				return this._PIC_BIC;
			}
			set
			{
				if ((this._PIC_BIC != value))
				{
					this._PIC_BIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_ISSUE_CODE", DbType="Int")]
		public System.Nullable<int> O_ISSUE_CODE
		{
			get
			{
				return this._O_ISSUE_CODE;
			}
			set
			{
				if ((this._O_ISSUE_CODE != value))
				{
					this._O_ISSUE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_DIVISION", DbType="Int")]
		public System.Nullable<int> O_DIVISION
		{
			get
			{
				return this._O_DIVISION;
			}
			set
			{
				if ((this._O_DIVISION != value))
				{
					this._O_DIVISION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_DIVISION_CODE", DbType="VarChar(10)")]
		public string O_DIVISION_CODE
		{
			get
			{
				return this._O_DIVISION_CODE;
			}
			set
			{
				if ((this._O_DIVISION_CODE != value))
				{
					this._O_DIVISION_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_DIVISION_NAME", DbType="NVarChar(255)")]
		public string O_DIVISION_NAME
		{
			get
			{
				return this._O_DIVISION_NAME;
			}
			set
			{
				if ((this._O_DIVISION_NAME != value))
				{
					this._O_DIVISION_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_STATUS_ID", DbType="Int")]
		public System.Nullable<int> O_STATUS_ID
		{
			get
			{
				return this._O_STATUS_ID;
			}
			set
			{
				if ((this._O_STATUS_ID != value))
				{
					this._O_STATUS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_STATUS", DbType="VarChar(25)")]
		public string O_STATUS
		{
			get
			{
				return this._O_STATUS;
			}
			set
			{
				if ((this._O_STATUS != value))
				{
					this._O_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SUMMARY", DbType="NVarChar(MAX)")]
		public string O_SUMMARY
		{
			get
			{
				return this._O_SUMMARY;
			}
			set
			{
				if ((this._O_SUMMARY != value))
				{
					this._O_SUMMARY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_AGREED_SOLUTION", DbType="NVarChar(MAX)")]
		public string O_AGREED_SOLUTION
		{
			get
			{
				return this._O_AGREED_SOLUTION;
			}
			set
			{
				if ((this._O_AGREED_SOLUTION != value))
				{
					this._O_AGREED_SOLUTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_DESCRIPTION", DbType="NVarChar(MAX)")]
		public string O_DESCRIPTION
		{
			get
			{
				return this._O_DESCRIPTION;
			}
			set
			{
				if ((this._O_DESCRIPTION != value))
				{
					this._O_DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_NOTE", DbType="NVarChar(MAX)")]
		public string O_NOTE
		{
			get
			{
				return this._O_NOTE;
			}
			set
			{
				if ((this._O_NOTE != value))
				{
					this._O_NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_FIRST_DATE_FB", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_FIRST_DATE_FB
		{
			get
			{
				return this._O_FIRST_DATE_FB;
			}
			set
			{
				if ((this._O_FIRST_DATE_FB != value))
				{
					this._O_FIRST_DATE_FB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_CURRENT_ASSIGNEE", DbType="NVarChar(55)")]
		public string O_CURRENT_ASSIGNEE
		{
			get
			{
				return this._O_CURRENT_ASSIGNEE;
			}
			set
			{
				if ((this._O_CURRENT_ASSIGNEE != value))
				{
					this._O_CURRENT_ASSIGNEE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_CREATION_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_CREATION_DATE
		{
			get
			{
				return this._O_CREATION_DATE;
			}
			set
			{
				if ((this._O_CREATION_DATE != value))
				{
					this._O_CREATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_EST_DEADLINE", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_EST_DEADLINE
		{
			get
			{
				return this._O_EST_DEADLINE;
			}
			set
			{
				if ((this._O_EST_DEADLINE != value))
				{
					this._O_EST_DEADLINE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_FINISHING_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_FINISHING_DATE
		{
			get
			{
				return this._O_FINISHING_DATE;
			}
			set
			{
				if ((this._O_FINISHING_DATE != value))
				{
					this._O_FINISHING_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_PENDING_DAYS", DbType="Float")]
		public System.Nullable<double> O_PENDING_DAYS
		{
			get
			{
				return this._O_PENDING_DAYS;
			}
			set
			{
				if ((this._O_PENDING_DAYS != value))
				{
					this._O_PENDING_DAYS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_PIC_BU", DbType="NVarChar(55)")]
		public string O_PIC_BU
		{
			get
			{
				return this._O_PIC_BU;
			}
			set
			{
				if ((this._O_PIC_BU != value))
				{
					this._O_PIC_BU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_PIC_BIC", DbType="NVarChar(55)")]
		public string O_PIC_BIC
		{
			get
			{
				return this._O_PIC_BIC;
			}
			set
			{
				if ((this._O_PIC_BIC != value))
				{
					this._O_PIC_BIC = value;
				}
			}
		}
	}
	
	public partial class uspDataIssueGetListAllDivisionIDResult
	{
		
		private System.Nullable<double> _Division_Id;
		
		private string _Division_Name;
		
		public uspDataIssueGetListAllDivisionIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division_Id", DbType="Float")]
		public System.Nullable<double> Division_Id
		{
			get
			{
				return this._Division_Id;
			}
			set
			{
				if ((this._Division_Id != value))
				{
					this._Division_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division_Name", DbType="NVarChar(255)")]
		public string Division_Name
		{
			get
			{
				return this._Division_Name;
			}
			set
			{
				if ((this._Division_Name != value))
				{
					this._Division_Name = value;
				}
			}
		}
	}
	
	public partial class uspDataIssueGetListDivisionIDResult
	{
		
		private System.Nullable<double> _Division_Id;
		
		private string _Division_Name;
		
		public uspDataIssueGetListDivisionIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division_Id", DbType="Float")]
		public System.Nullable<double> Division_Id
		{
			get
			{
				return this._Division_Id;
			}
			set
			{
				if ((this._Division_Id != value))
				{
					this._Division_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division_Name", DbType="NVarChar(255)")]
		public string Division_Name
		{
			get
			{
				return this._Division_Name;
			}
			set
			{
				if ((this._Division_Name != value))
				{
					this._Division_Name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
