#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VPBReportBackup20170724")]
	public partial class ReportDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ReportDataContext() : 
				base(global::DataContext.Properties.Settings.Default.VPBReportBackup20170724ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReportDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportDelete")]
		public int uspReportDelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportUpdateStatus")]
		public int uspReportUpdateStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string description)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportId, status, description);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportGetById")]
		public ISingleResult<uspReportGetByIdResult> uspReportGetById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportId);
			return ((ISingleResult<uspReportGetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportListUpdateStatus")]
		public int uspReportListUpdateStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportCreateByFrequency")]
		public int uspReportCreateByFrequency([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> toDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> action)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId, fromDate, toDate, action);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportListGetListClient")]
		public ISingleResult<uspReportListGetListClientResult> uspReportListGetListClient([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId);
			return ((ISingleResult<uspReportListGetListClientResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportListRemoveClient")]
		public int uspReportListRemoveClient([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> clientId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportListUpdateClient")]
		public int uspReportListUpdateClient([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string adminIds, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminIds, reportListId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportGetListForClient")]
		public ISingleResult<uspReportGetListForClientResult> uspReportGetListForClient([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> adminId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> toDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> totalRecord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminId, fromDate, toDate, page, pageSize, totalRecord);
			totalRecord = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((ISingleResult<uspReportGetListForClientResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportListGetClient")]
		public ISingleResult<uspReportListGetClientResult> uspReportListGetClient([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string accountName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId, accountName);
			return ((ISingleResult<uspReportListGetClientResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspRequestFormUpdate")]
		public int uspRequestFormUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string requestForm)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId, requestForm);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSendEmailReport")]
		public ISingleResult<uspSendEmailReportResult> uspSendEmailReport()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspSendEmailReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportListUpdateTotalDownload")]
		public int uspReportListUpdateTotalDownload([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string fileName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportGetListForView")]
		public ISingleResult<uspReportGetListForViewResult> uspReportGetListForView([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string reportName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string accountName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> departmentId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> toDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> totalRecord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportName, accountName, departmentId, fromDate, toDate, page, pageSize, totalRecord);
			totalRecord = ((System.Nullable<int>)(result.GetParameterValue(7)));
			return ((ISingleResult<uspReportGetListForViewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportUpload")]
		public int uspReportUpload([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string fileName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string accountUpload, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string timeKeyData, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string linkReport)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportId, fileName, accountUpload, timeKeyData, linkReport);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportListInsert")]
		public int uspReportListInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string requestId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string accountBackup, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isAuto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string toolOfReport)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestId, account, accountBackup, isAuto, toolOfReport);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportListUpdate")]
		public int uspReportListUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string requestId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string accountBackup, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isAuto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string toolOfReport)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId, requestId, account, accountBackup, isAuto, toolOfReport);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportListGetInfo")]
		public ISingleResult<uspReportListGetInfoResult> uspReportListGetInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId);
			return ((ISingleResult<uspReportListGetInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportListGetList")]
		public ISingleResult<uspReportListGetListResult> uspReportListGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string reportName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> departmentId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> frequency, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportName, departmentId, frequency, account, status);
			return ((ISingleResult<uspReportListGetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportGetList")]
		public ISingleResult<uspReportGetListResult> uspReportGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string reportName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pic, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportUpdateType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> managerId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> frequency, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string accountName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> toDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isComplete, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isBackup, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> totalRecord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportName, pic, reportType, reportUpdateType, managerId, frequency, accountName, fromDate, toDate, isComplete, status, isBackup, page, pageSize, totalRecord);
			totalRecord = ((System.Nullable<int>)(result.GetParameterValue(14)));
			return ((ISingleResult<uspReportGetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspReportInsert")]
		public int uspReportInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateExpire)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId, dateExpire);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class uspReportGetByIdResult
	{
		
		private int _ReportId;
		
		private int _Frequency;
		
		private string _ReportName;
		
		private string _FileName;
		
		private System.DateTime _DateExpire;
		
		private System.Nullable<System.DateTime> _DateUpload;
		
		private System.Nullable<System.DateTime> _TimeKeyData;
		
		private string _Account;
		
		private string _AccountBackup;
		
		private string _Description;
		
		private int _Status;
		
		public uspReportGetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportId", DbType="Int NOT NULL")]
		public int ReportId
		{
			get
			{
				return this._ReportId;
			}
			set
			{
				if ((this._ReportId != value))
				{
					this._ReportId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="Int NOT NULL")]
		public int Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this._ReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(100)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpire", DbType="DateTime NOT NULL")]
		public System.DateTime DateExpire
		{
			get
			{
				return this._DateExpire;
			}
			set
			{
				if ((this._DateExpire != value))
				{
					this._DateExpire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpload", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpload
		{
			get
			{
				return this._DateUpload;
			}
			set
			{
				if ((this._DateUpload != value))
				{
					this._DateUpload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeKeyData", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeKeyData
		{
			get
			{
				return this._TimeKeyData;
			}
			set
			{
				if ((this._TimeKeyData != value))
				{
					this._TimeKeyData = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBackup", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountBackup
		{
			get
			{
				return this._AccountBackup;
			}
			set
			{
				if ((this._AccountBackup != value))
				{
					this._AccountBackup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class uspReportListGetListClientResult
	{
		
		private int _Id;
		
		private int _AdminId;
		
		private string _Name;
		
		private string _FullName;
		
		public uspReportListGetListClientResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminId", DbType="Int NOT NULL")]
		public int AdminId
		{
			get
			{
				return this._AdminId;
			}
			set
			{
				if ((this._AdminId != value))
				{
					this._AdminId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(250)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
	}
	
	public partial class uspReportGetListForClientResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private int _ReportId;
		
		private string _Frequency;
		
		private string _StatusComplete;
		
		private string _ReportName;
		
		private string _ReportCode;
		
		private string _FileName;
		
		private System.DateTime _DateExpire;
		
		private string _Deadline;
		
		private System.Nullable<System.DateTime> _DateUpload;
		
		private string _Client;
		
		private System.Nullable<System.DateTime> _TimeKeyData;
		
		private string _Account;
		
		private string _AccountBackup;
		
		private string _Description;
		
		private int _Status;
		
		private string _RLDescription;
		
		private string _Department;
		
		public uspReportGetListForClientResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportId", DbType="Int NOT NULL")]
		public int ReportId
		{
			get
			{
				return this._ReportId;
			}
			set
			{
				if ((this._ReportId != value))
				{
					this._ReportId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="VarChar(7)")]
		public string Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusComplete", DbType="VarChar(12)")]
		public string StatusComplete
		{
			get
			{
				return this._StatusComplete;
			}
			set
			{
				if ((this._StatusComplete != value))
				{
					this._StatusComplete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this._ReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ReportCode
		{
			get
			{
				return this._ReportCode;
			}
			set
			{
				if ((this._ReportCode != value))
				{
					this._ReportCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(100)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpire", DbType="DateTime NOT NULL")]
		public System.DateTime DateExpire
		{
			get
			{
				return this._DateExpire;
			}
			set
			{
				if ((this._DateExpire != value))
				{
					this._DateExpire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deadline", DbType="VarChar(50)")]
		public string Deadline
		{
			get
			{
				return this._Deadline;
			}
			set
			{
				if ((this._Deadline != value))
				{
					this._Deadline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpload", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpload
		{
			get
			{
				return this._DateUpload;
			}
			set
			{
				if ((this._DateUpload != value))
				{
					this._DateUpload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this._Client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeKeyData", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeKeyData
		{
			get
			{
				return this._TimeKeyData;
			}
			set
			{
				if ((this._TimeKeyData != value))
				{
					this._TimeKeyData = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBackup", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountBackup
		{
			get
			{
				return this._AccountBackup;
			}
			set
			{
				if ((this._AccountBackup != value))
				{
					this._AccountBackup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RLDescription", DbType="NVarChar(200)")]
		public string RLDescription
		{
			get
			{
				return this._RLDescription;
			}
			set
			{
				if ((this._RLDescription != value))
				{
					this._RLDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(2)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
	}
	
	public partial class uspReportListGetClientResult
	{
		
		private int _AdminId;
		
		private string _Name;
		
		private string _FullName;
		
		public uspReportListGetClientResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminId", DbType="Int NOT NULL")]
		public int AdminId
		{
			get
			{
				return this._AdminId;
			}
			set
			{
				if ((this._AdminId != value))
				{
					this._AdminId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(250)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
	}
	
	public partial class uspSendEmailReportResult
	{
		
		private string _Account;
		
		private System.Nullable<int> _TotalReport;
		
		public uspSendEmailReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReport", DbType="Int")]
		public System.Nullable<int> TotalReport
		{
			get
			{
				return this._TotalReport;
			}
			set
			{
				if ((this._TotalReport != value))
				{
					this._TotalReport = value;
				}
			}
		}
	}
	
	public partial class uspReportGetListForViewResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private int _ReportId;
		
		private string _Frequency;
		
		private string _DepartmentName;
		
		private string _ReportName;
		
		private string _ReportCode;
		
		private string _FileName;
		
		private System.DateTime _DateExpire;
		
		private string _Deadline;
		
		private System.Nullable<System.DateTime> _DateUpload;
		
		private string _Client;
		
		private System.Nullable<System.DateTime> _TimeKeyData;
		
		private string _Account;
		
		private string _AccountBackup;
		
		private string _Description;
		
		private int _Status;
		
		private string _RLDescription;
		
		private string _Department;
		
		public uspReportGetListForViewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportId", DbType="Int NOT NULL")]
		public int ReportId
		{
			get
			{
				return this._ReportId;
			}
			set
			{
				if ((this._ReportId != value))
				{
					this._ReportId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="VarChar(7)")]
		public string Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DepartmentName
		{
			get
			{
				return this._DepartmentName;
			}
			set
			{
				if ((this._DepartmentName != value))
				{
					this._DepartmentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this._ReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportCode", DbType="VarChar(50)")]
		public string ReportCode
		{
			get
			{
				return this._ReportCode;
			}
			set
			{
				if ((this._ReportCode != value))
				{
					this._ReportCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(100)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpire", DbType="DateTime NOT NULL")]
		public System.DateTime DateExpire
		{
			get
			{
				return this._DateExpire;
			}
			set
			{
				if ((this._DateExpire != value))
				{
					this._DateExpire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deadline", DbType="VarChar(50)")]
		public string Deadline
		{
			get
			{
				return this._Deadline;
			}
			set
			{
				if ((this._Deadline != value))
				{
					this._Deadline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpload", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpload
		{
			get
			{
				return this._DateUpload;
			}
			set
			{
				if ((this._DateUpload != value))
				{
					this._DateUpload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this._Client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeKeyData", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeKeyData
		{
			get
			{
				return this._TimeKeyData;
			}
			set
			{
				if ((this._TimeKeyData != value))
				{
					this._TimeKeyData = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBackup", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountBackup
		{
			get
			{
				return this._AccountBackup;
			}
			set
			{
				if ((this._AccountBackup != value))
				{
					this._AccountBackup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RLDescription", DbType="NVarChar(200)")]
		public string RLDescription
		{
			get
			{
				return this._RLDescription;
			}
			set
			{
				if ((this._RLDescription != value))
				{
					this._RLDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(2)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
	}
	
	public partial class uspReportListGetInfoResult
	{
		
		private int _ReportListId;
		
		private int _DepartmentId;
		
		private string _ReportName;
		
		private string _Client;
		
		private string _EmailClient;
		
		private string _Deadline;
		
		private string _Frequency;
		
		private string _Description;
		
		private string _Account;
		
		private string _AccountBackup;
		
		private int _IsAuto;
		
		private System.Nullable<int> _Request_Id;
		
		public uspReportListGetInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportListId", DbType="Int NOT NULL")]
		public int ReportListId
		{
			get
			{
				return this._ReportListId;
			}
			set
			{
				if ((this._ReportListId != value))
				{
					this._ReportListId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentId", DbType="Int NOT NULL")]
		public int DepartmentId
		{
			get
			{
				return this._DepartmentId;
			}
			set
			{
				if ((this._DepartmentId != value))
				{
					this._DepartmentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="NVarChar(250)")]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this._ReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this._Client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailClient", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailClient
		{
			get
			{
				return this._EmailClient;
			}
			set
			{
				if ((this._EmailClient != value))
				{
					this._EmailClient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deadline", DbType="NVarChar(50)")]
		public string Deadline
		{
			get
			{
				return this._Deadline;
			}
			set
			{
				if ((this._Deadline != value))
				{
					this._Deadline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="NVarChar(MAX)")]
		public string Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50)")]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBackup", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountBackup
		{
			get
			{
				return this._AccountBackup;
			}
			set
			{
				if ((this._AccountBackup != value))
				{
					this._AccountBackup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAuto", DbType="Int NOT NULL")]
		public int IsAuto
		{
			get
			{
				return this._IsAuto;
			}
			set
			{
				if ((this._IsAuto != value))
				{
					this._IsAuto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Request_Id", DbType="Int")]
		public System.Nullable<int> Request_Id
		{
			get
			{
				return this._Request_Id;
			}
			set
			{
				if ((this._Request_Id != value))
				{
					this._Request_Id = value;
				}
			}
		}
	}
	
	public partial class uspReportListGetListResult
	{
		
		private int _ReportListId;
		
		private int _DepartmentId;
		
		private string _ReportName;
		
		private string _ReportCode;
		
		private System.Nullable<int> _RequestId;
		
		private string _Client;
		
		private string _EmailClient;
		
		private string _Deadline;
		
		private string _Department;
		
		private string _Frequency;
		
		private string _Account;
		
		private int _Status;
		
		private string _AccountBackup;
		
		private int _IsAuto;
		
		private string _Description;
		
		private string _RequestForm;
		
		private int _TotalDownload;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public uspReportListGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportListId", DbType="Int NOT NULL")]
		public int ReportListId
		{
			get
			{
				return this._ReportListId;
			}
			set
			{
				if ((this._ReportListId != value))
				{
					this._ReportListId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentId", DbType="Int NOT NULL")]
		public int DepartmentId
		{
			get
			{
				return this._DepartmentId;
			}
			set
			{
				if ((this._DepartmentId != value))
				{
					this._DepartmentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="NVarChar(250)")]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this._ReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportCode", DbType="VarChar(50)")]
		public string ReportCode
		{
			get
			{
				return this._ReportCode;
			}
			set
			{
				if ((this._ReportCode != value))
				{
					this._ReportCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestId", DbType="Int")]
		public System.Nullable<int> RequestId
		{
			get
			{
				return this._RequestId;
			}
			set
			{
				if ((this._RequestId != value))
				{
					this._RequestId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this._Client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailClient", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailClient
		{
			get
			{
				return this._EmailClient;
			}
			set
			{
				if ((this._EmailClient != value))
				{
					this._EmailClient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deadline", DbType="NVarChar(50)")]
		public string Deadline
		{
			get
			{
				return this._Deadline;
			}
			set
			{
				if ((this._Deadline != value))
				{
					this._Deadline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="VarChar(8)")]
		public string Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50)")]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBackup", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountBackup
		{
			get
			{
				return this._AccountBackup;
			}
			set
			{
				if ((this._AccountBackup != value))
				{
					this._AccountBackup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAuto", DbType="Int NOT NULL")]
		public int IsAuto
		{
			get
			{
				return this._IsAuto;
			}
			set
			{
				if ((this._IsAuto != value))
				{
					this._IsAuto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestForm", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string RequestForm
		{
			get
			{
				return this._RequestForm;
			}
			set
			{
				if ((this._RequestForm != value))
				{
					this._RequestForm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDownload", DbType="Int NOT NULL")]
		public int TotalDownload
		{
			get
			{
				return this._TotalDownload;
			}
			set
			{
				if ((this._TotalDownload != value))
				{
					this._TotalDownload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	public partial class uspReportGetListResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private int _ReportId;
		
		private string _Frequency;
		
		private string _ReportName;
		
		private string _ReportCode;
		
		private int _ReportListId;
		
		private string _FileName;
		
		private System.DateTime _DateExpire;
		
		private System.Nullable<System.DateTime> _DateUpload;
		
		private System.Nullable<System.DateTime> _TimeKeyData;
		
		private string _Account;
		
		private string _AccountBackup;
		
		private string _AccountUpload;
		
		private string _Description;
		
		private string _RLDescription;
		
		private System.Nullable<int> _IsComplete;
		
		private string _StatusComplete;
		
		private int _Status;
		
		private string _Client;
		
		private string _Deadline;
		
		private string _IsAuto;
		
		private string _Department;
		
		private string _ReportType;
		
		public uspReportGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportId", DbType="Int NOT NULL")]
		public int ReportId
		{
			get
			{
				return this._ReportId;
			}
			set
			{
				if ((this._ReportId != value))
				{
					this._ReportId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="VarChar(8)")]
		public string Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="NVarChar(250)")]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this._ReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportCode", DbType="VarChar(50)")]
		public string ReportCode
		{
			get
			{
				return this._ReportCode;
			}
			set
			{
				if ((this._ReportCode != value))
				{
					this._ReportCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportListId", DbType="Int NOT NULL")]
		public int ReportListId
		{
			get
			{
				return this._ReportListId;
			}
			set
			{
				if ((this._ReportListId != value))
				{
					this._ReportListId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(100)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpire", DbType="DateTime NOT NULL")]
		public System.DateTime DateExpire
		{
			get
			{
				return this._DateExpire;
			}
			set
			{
				if ((this._DateExpire != value))
				{
					this._DateExpire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpload", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpload
		{
			get
			{
				return this._DateUpload;
			}
			set
			{
				if ((this._DateUpload != value))
				{
					this._DateUpload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeKeyData", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeKeyData
		{
			get
			{
				return this._TimeKeyData;
			}
			set
			{
				if ((this._TimeKeyData != value))
				{
					this._TimeKeyData = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50)")]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBackup", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountBackup
		{
			get
			{
				return this._AccountBackup;
			}
			set
			{
				if ((this._AccountBackup != value))
				{
					this._AccountBackup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountUpload", DbType="NVarChar(50)")]
		public string AccountUpload
		{
			get
			{
				return this._AccountUpload;
			}
			set
			{
				if ((this._AccountUpload != value))
				{
					this._AccountUpload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RLDescription", DbType="NVarChar(MAX)")]
		public string RLDescription
		{
			get
			{
				return this._RLDescription;
			}
			set
			{
				if ((this._RLDescription != value))
				{
					this._RLDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsComplete", DbType="Int")]
		public System.Nullable<int> IsComplete
		{
			get
			{
				return this._IsComplete;
			}
			set
			{
				if ((this._IsComplete != value))
				{
					this._IsComplete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusComplete", DbType="VarChar(8)")]
		public string StatusComplete
		{
			get
			{
				return this._StatusComplete;
			}
			set
			{
				if ((this._StatusComplete != value))
				{
					this._StatusComplete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="NVarChar(50)")]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this._Client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deadline", DbType="NVarChar(50)")]
		public string Deadline
		{
			get
			{
				return this._Deadline;
			}
			set
			{
				if ((this._Deadline != value))
				{
					this._Deadline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAuto", DbType="VarChar(6)")]
		public string IsAuto
		{
			get
			{
				return this._IsAuto;
			}
			set
			{
				if ((this._IsAuto != value))
				{
					this._IsAuto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportType", DbType="VarChar(7)")]
		public string ReportType
		{
			get
			{
				return this._ReportType;
			}
			set
			{
				if ((this._ReportType != value))
				{
					this._ReportType = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
