#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VPBReportBackup20170724")]
	public partial class RequestReportDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public RequestReportDataContext() : 
				base(global::DataContext.Properties.Settings.Default.VPBReportBackup20170724ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RequestReportDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RequestReportDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RequestReportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RequestReportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspRequestReportListInsert")]
		public int uspRequestReportListInsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string requestName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string client, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string emailClient, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> requestType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string receive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> requestStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string deadline, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> requestSendType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string reportType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string requestDescription, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string frequency, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> noTracerReceived, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> noTracerResolved, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string requestReasonCan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string requestDiscussMan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string requestInformClient)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestName, client, emailClient, requestType, receive, requestStatus, deadline, account, requestSendType, reportType, requestDescription, frequency, noTracerReceived, noTracerResolved, requestReasonCan, requestDiscussMan, requestInformClient);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspRequestReportListGetList")]
		public ISingleResult<uspRequestReportListGetListResult> uspRequestReportListGetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string requestName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string receiveFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string receiveTo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> department, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pic, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> totalRecord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestName, receiveFrom, receiveTo, department, account, status, pic, page, pageSize, totalRecord);
			totalRecord = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((ISingleResult<uspRequestReportListGetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspRequestReportListUpdate")]
		public int uspRequestReportListUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string reportName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string client, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string emailClient, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> requestType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string receive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> requestStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string deadline, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> requestSendType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string reportType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string requestDescription, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string frequency, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> noTracerReceived, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> noTracerResolved, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string requestReasonCan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string requestDiscussMan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string requestInformClient)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportName, reportListId, client, emailClient, requestType, receive, requestStatus, deadline, requestSendType, reportType, requestDescription, frequency, noTracerReceived, noTracerResolved, requestReasonCan, requestDiscussMan, requestInformClient);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspRequestReportGetInfoCreateReport")]
		public ISingleResult<uspRequestReportGetInfoCreateReportResult> uspRequestReportGetInfoCreateReport([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string accountName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId, accountName);
			return ((ISingleResult<uspRequestReportGetInfoCreateReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspRequestReportGetInfo")]
		public ISingleResult<uspRequestReportGetInfoResult> uspRequestReportGetInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reportListId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportListId);
			return ((ISingleResult<uspRequestReportGetInfoResult>)(result.ReturnValue));
		}
	}
	
	public partial class uspRequestReportListGetListResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private int _REQUEST_ID;
		
		private string _CLIENT_EMAIL;
		
		private string _REQUEST_NAME;
		
		private string _CLIENT_DIVISION;
		
		private string _ACCOUNT;
		
		private string _REQUEST_TYPE;
		
		private System.Nullable<System.DateTime> _RECEIVED_DATE;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _STATUS;
		
		private string _DELIVERED_DATE;
		
		private string _SENDING_TYPE;
		
		private string _REPORT_CODE;
		
		private string _DEPARTMENT;
		
		private string _Decription;
		
		public uspRequestReportListGetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUEST_ID", DbType="Int NOT NULL")]
		public int REQUEST_ID
		{
			get
			{
				return this._REQUEST_ID;
			}
			set
			{
				if ((this._REQUEST_ID != value))
				{
					this._REQUEST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_EMAIL", DbType="NVarChar(50)")]
		public string CLIENT_EMAIL
		{
			get
			{
				return this._CLIENT_EMAIL;
			}
			set
			{
				if ((this._CLIENT_EMAIL != value))
				{
					this._CLIENT_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUEST_NAME", DbType="NVarChar(250)")]
		public string REQUEST_NAME
		{
			get
			{
				return this._REQUEST_NAME;
			}
			set
			{
				if ((this._REQUEST_NAME != value))
				{
					this._REQUEST_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_DIVISION", DbType="NVarChar(255)")]
		public string CLIENT_DIVISION
		{
			get
			{
				return this._CLIENT_DIVISION;
			}
			set
			{
				if ((this._CLIENT_DIVISION != value))
				{
					this._CLIENT_DIVISION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT", DbType="NVarChar(50)")]
		public string ACCOUNT
		{
			get
			{
				return this._ACCOUNT;
			}
			set
			{
				if ((this._ACCOUNT != value))
				{
					this._ACCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUEST_TYPE", DbType="VarChar(14)")]
		public string REQUEST_TYPE
		{
			get
			{
				return this._REQUEST_TYPE;
			}
			set
			{
				if ((this._REQUEST_TYPE != value))
				{
					this._REQUEST_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIVED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RECEIVED_DATE
		{
			get
			{
				return this._RECEIVED_DATE;
			}
			set
			{
				if ((this._RECEIVED_DATE != value))
				{
					this._RECEIVED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this._CREATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(25)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELIVERED_DATE", DbType="NVarChar(50)")]
		public string DELIVERED_DATE
		{
			get
			{
				return this._DELIVERED_DATE;
			}
			set
			{
				if ((this._DELIVERED_DATE != value))
				{
					this._DELIVERED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENDING_TYPE", DbType="VarChar(6)")]
		public string SENDING_TYPE
		{
			get
			{
				return this._SENDING_TYPE;
			}
			set
			{
				if ((this._SENDING_TYPE != value))
				{
					this._SENDING_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORT_CODE", DbType="NVarChar(50)")]
		public string REPORT_CODE
		{
			get
			{
				return this._REPORT_CODE;
			}
			set
			{
				if ((this._REPORT_CODE != value))
				{
					this._REPORT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DEPARTMENT
		{
			get
			{
				return this._DEPARTMENT;
			}
			set
			{
				if ((this._DEPARTMENT != value))
				{
					this._DEPARTMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Decription", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Decription
		{
			get
			{
				return this._Decription;
			}
			set
			{
				if ((this._Decription != value))
				{
					this._Decription = value;
				}
			}
		}
	}
	
	public partial class uspRequestReportGetInfoCreateReportResult
	{
		
		private System.Nullable<int> _Request_Id;
		
		private string _Request_Name;
		
		private string _Received_Date;
		
		private string _Client_Email;
		
		private string _Client_Division;
		
		private string _Created_Date;
		
		private string _Account;
		
		private string _Status;
		
		private string _Delivered_Date;
		
		private string _Sending_Type;
		
		private string _Report_Code;
		
		private string _Request_Type;
		
		private string _Decription;
		
		private string _Frequency;
		
		private System.Nullable<int> _No_tracer_received;
		
		private System.Nullable<int> _No_tracer_solved;
		
		private string _Reason_cancel_reject;
		
		private string _Discuss_Man;
		
		private string _Inform_Email;
		
		public uspRequestReportGetInfoCreateReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Request_Id", DbType="Int")]
		public System.Nullable<int> Request_Id
		{
			get
			{
				return this._Request_Id;
			}
			set
			{
				if ((this._Request_Id != value))
				{
					this._Request_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Request_Name", DbType="NVarChar(250)")]
		public string Request_Name
		{
			get
			{
				return this._Request_Name;
			}
			set
			{
				if ((this._Request_Name != value))
				{
					this._Request_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Received_Date", DbType="NVarChar(15)")]
		public string Received_Date
		{
			get
			{
				return this._Received_Date;
			}
			set
			{
				if ((this._Received_Date != value))
				{
					this._Received_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_Email", DbType="NVarChar(50)")]
		public string Client_Email
		{
			get
			{
				return this._Client_Email;
			}
			set
			{
				if ((this._Client_Email != value))
				{
					this._Client_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_Division", DbType="NVarChar(50)")]
		public string Client_Division
		{
			get
			{
				return this._Client_Division;
			}
			set
			{
				if ((this._Client_Division != value))
				{
					this._Client_Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Date", DbType="NVarChar(15)")]
		public string Created_Date
		{
			get
			{
				return this._Created_Date;
			}
			set
			{
				if ((this._Created_Date != value))
				{
					this._Created_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50)")]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delivered_Date", DbType="NVarChar(15)")]
		public string Delivered_Date
		{
			get
			{
				return this._Delivered_Date;
			}
			set
			{
				if ((this._Delivered_Date != value))
				{
					this._Delivered_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sending_Type", DbType="NVarChar(50)")]
		public string Sending_Type
		{
			get
			{
				return this._Sending_Type;
			}
			set
			{
				if ((this._Sending_Type != value))
				{
					this._Sending_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Code", DbType="NVarChar(50)")]
		public string Report_Code
		{
			get
			{
				return this._Report_Code;
			}
			set
			{
				if ((this._Report_Code != value))
				{
					this._Report_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Request_Type", DbType="NVarChar(50)")]
		public string Request_Type
		{
			get
			{
				return this._Request_Type;
			}
			set
			{
				if ((this._Request_Type != value))
				{
					this._Request_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Decription", DbType="NVarChar(MAX)")]
		public string Decription
		{
			get
			{
				return this._Decription;
			}
			set
			{
				if ((this._Decription != value))
				{
					this._Decription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="NVarChar(MAX)")]
		public string Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_tracer_received", DbType="Int")]
		public System.Nullable<int> No_tracer_received
		{
			get
			{
				return this._No_tracer_received;
			}
			set
			{
				if ((this._No_tracer_received != value))
				{
					this._No_tracer_received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_tracer_solved", DbType="Int")]
		public System.Nullable<int> No_tracer_solved
		{
			get
			{
				return this._No_tracer_solved;
			}
			set
			{
				if ((this._No_tracer_solved != value))
				{
					this._No_tracer_solved = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_cancel_reject", DbType="NVarChar(MAX)")]
		public string Reason_cancel_reject
		{
			get
			{
				return this._Reason_cancel_reject;
			}
			set
			{
				if ((this._Reason_cancel_reject != value))
				{
					this._Reason_cancel_reject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discuss_Man", DbType="NVarChar(50)")]
		public string Discuss_Man
		{
			get
			{
				return this._Discuss_Man;
			}
			set
			{
				if ((this._Discuss_Man != value))
				{
					this._Discuss_Man = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inform_Email", DbType="NVarChar(50)")]
		public string Inform_Email
		{
			get
			{
				return this._Inform_Email;
			}
			set
			{
				if ((this._Inform_Email != value))
				{
					this._Inform_Email = value;
				}
			}
		}
	}
	
	public partial class uspRequestReportGetInfoResult
	{
		
		private System.Nullable<int> _Request_Id;
		
		private string _Request_Name;
		
		private string _Received_Date;
		
		private string _Client_Email;
		
		private string _Client_Division;
		
		private string _Created_Date;
		
		private string _Account;
		
		private string _Status;
		
		private string _Delivered_Date;
		
		private string _Sending_Type;
		
		private string _Report_Code;
		
		private string _Request_Type;
		
		private string _Decription;
		
		private string _Frequency;
		
		private System.Nullable<int> _No_tracer_received;
		
		private System.Nullable<int> _No_tracer_solved;
		
		private string _Reason_cancel_reject;
		
		private string _Discuss_Man;
		
		private string _Inform_Email;
		
		private string _Report_Type;
		
		public uspRequestReportGetInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Request_Id", DbType="Int")]
		public System.Nullable<int> Request_Id
		{
			get
			{
				return this._Request_Id;
			}
			set
			{
				if ((this._Request_Id != value))
				{
					this._Request_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Request_Name", DbType="NVarChar(250)")]
		public string Request_Name
		{
			get
			{
				return this._Request_Name;
			}
			set
			{
				if ((this._Request_Name != value))
				{
					this._Request_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Received_Date", DbType="NVarChar(15)")]
		public string Received_Date
		{
			get
			{
				return this._Received_Date;
			}
			set
			{
				if ((this._Received_Date != value))
				{
					this._Received_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_Email", DbType="NVarChar(50)")]
		public string Client_Email
		{
			get
			{
				return this._Client_Email;
			}
			set
			{
				if ((this._Client_Email != value))
				{
					this._Client_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_Division", DbType="NVarChar(50)")]
		public string Client_Division
		{
			get
			{
				return this._Client_Division;
			}
			set
			{
				if ((this._Client_Division != value))
				{
					this._Client_Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Date", DbType="NVarChar(15)")]
		public string Created_Date
		{
			get
			{
				return this._Created_Date;
			}
			set
			{
				if ((this._Created_Date != value))
				{
					this._Created_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(50)")]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delivered_Date", DbType="NVarChar(15)")]
		public string Delivered_Date
		{
			get
			{
				return this._Delivered_Date;
			}
			set
			{
				if ((this._Delivered_Date != value))
				{
					this._Delivered_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sending_Type", DbType="NVarChar(50)")]
		public string Sending_Type
		{
			get
			{
				return this._Sending_Type;
			}
			set
			{
				if ((this._Sending_Type != value))
				{
					this._Sending_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Code", DbType="NVarChar(50)")]
		public string Report_Code
		{
			get
			{
				return this._Report_Code;
			}
			set
			{
				if ((this._Report_Code != value))
				{
					this._Report_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Request_Type", DbType="NVarChar(50)")]
		public string Request_Type
		{
			get
			{
				return this._Request_Type;
			}
			set
			{
				if ((this._Request_Type != value))
				{
					this._Request_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Decription", DbType="NVarChar(MAX)")]
		public string Decription
		{
			get
			{
				return this._Decription;
			}
			set
			{
				if ((this._Decription != value))
				{
					this._Decription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="NVarChar(50)")]
		public string Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_tracer_received", DbType="Int")]
		public System.Nullable<int> No_tracer_received
		{
			get
			{
				return this._No_tracer_received;
			}
			set
			{
				if ((this._No_tracer_received != value))
				{
					this._No_tracer_received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_tracer_solved", DbType="Int")]
		public System.Nullable<int> No_tracer_solved
		{
			get
			{
				return this._No_tracer_solved;
			}
			set
			{
				if ((this._No_tracer_solved != value))
				{
					this._No_tracer_solved = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_cancel_reject", DbType="NVarChar(MAX)")]
		public string Reason_cancel_reject
		{
			get
			{
				return this._Reason_cancel_reject;
			}
			set
			{
				if ((this._Reason_cancel_reject != value))
				{
					this._Reason_cancel_reject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discuss_Man", DbType="NVarChar(50)")]
		public string Discuss_Man
		{
			get
			{
				return this._Discuss_Man;
			}
			set
			{
				if ((this._Discuss_Man != value))
				{
					this._Discuss_Man = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inform_Email", DbType="NVarChar(50)")]
		public string Inform_Email
		{
			get
			{
				return this._Inform_Email;
			}
			set
			{
				if ((this._Inform_Email != value))
				{
					this._Inform_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Type", DbType="NVarChar(50)")]
		public string Report_Type
		{
			get
			{
				return this._Report_Type;
			}
			set
			{
				if ((this._Report_Type != value))
				{
					this._Report_Type = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
